import './SubPages.css'
import { useEffect, useContext, useState } from 'react'
import NavBar from './NavBar'
import Footer from './Footer'
import ContextProvider from '../../Resources/ContextProvider'

const LegalPage = ({ type = 'privacy' }) => {
  const { storePath } = useContext(ContextProvider)
  
  const contentMap = {
    privacy: {
      title: 'Privacy Policy',
      kicker: '🔒 Your Data Matters',
      desc: 'Comprehensive information on how Enterprise Compute handles and protects your organizational data.',
      lastUpdated: 'May 11, 2026',
      fullContent: (
        <div className="sp-legal-rich-content">
          <p>This Privacy Policy describes our policies and procedures on the collection, use, and disclosure of your information when you use the Service and tells you about your privacy rights and how the law protects you.</p>

          <h3>1. Interpretation and Definitions</h3>
          <h4>Interpretation</h4>
          <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
          
          <h4>Definitions</h4>
          <ul>
            <li><strong>Account:</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><strong>Company:</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Enterprise Compute Central.</li>
            <li><strong>Service:</strong> refers to the Enterprise Compute Platform and all associated operational modules.</li>
            <li><strong>Usage Data:</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
          </ul>

          <h3>2. Collecting and Using Your Personal Data</h3>
          <h4>Types of Data Collected</h4>
          
          <h5>A. Personal & Account Data</h5>
          <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
          <ul>
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Company/Organization Name</li>
            <li>Billing Address and Payment Information (processed via secure third-party gateways)</li>
          </ul>

          <h5>B. Operational & Enterprise Data</h5>
          <p>Given the nature of the Service as an Enterprise Resource Planning (ERP) platform, we collect and process data critical to your business operations. This includes:</p>
          <ul>
            <li><strong>HR & Payroll Records:</strong> Employee identities, attendance logs, salary structures, and compensation history.</li>
            <li><strong>Financial & Accounting Data:</strong> General Ledger entries, Accounts Payable/Receivable, and transaction journals.</li>
            <li><strong>Commercial Data:</strong> Point of Sale (POS) transaction records, customer purchase history, and sales analytics.</li>
            <li><strong>Inventory Data:</strong> Stock levels, warehouse movements, and procurement logs.</li>
          </ul>

          <h5>C. Usage Data & Technical Logs</h5>
          <p>Usage Data is collected automatically when using the Service. This includes Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>

          <h3>3. Use of Your Personal Data</h3>
          <p>The Company may use Personal Data for the following purposes:</p>
          <ul>
            <li><strong>To provide and maintain our Service:</strong> including to monitor the usage of our Service and ensure real-time synchronization across your organization.</li>
            <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service and provide access to administrative functionalities.</li>
            <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.</li>
            <li><strong>To contact You:</strong> by email, telephone calls, or other equivalent forms of electronic communication regarding updates or informative communications related to the functionalities.</li>
          </ul>

          <h3>4. Data Retention & Security</h3>
          <h4>Retention of Data</h4>
          <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
          
          <h4>Security of Data</h4>
          <p>The security of Your Personal Data is important to Us. We use industry-standard encryption (AES-256 at rest, TLS 1.3 in transit) to protect your organizational records. However, remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

          <h3>5. Your Rights and Choices</h3>
          <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. Our Service gives You the ability to delete certain information about You from within the Service (e.g. Employee records or User profiles).</p>
          <p>You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us. Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>

          <h3>6. Contact Us</h3>
          <p>If you have any questions about this Privacy Policy, You can contact us:</p>
          <ul>
            <li>By email: legal@epxcentral.com</li>
            <li>By visiting this page on our website: /help</li>
          </ul>
        </div>
      )
    },
    terms: {
      title: 'Terms of Service',
      kicker: '📜 Standard Agreement',
      desc: 'The legal framework for using the Enterprise Compute platform.',
      lastUpdated: 'April 15, 2026'
    },
    cookies: {
      title: 'Cookie Policy',
      kicker: '🍪 Browser Data',
      desc: 'Information about how we use cookies to improve your experience.',
      lastUpdated: 'March 20, 2026'
    },
    security: {
      title: 'Security Overview',
      kicker: '🛡️ Enterprise Protection',
      desc: 'Our commitment to keeping your business data safe and available.',
      lastUpdated: 'May 05, 2026'
    }
  }

  const active = contentMap[type] || contentMap.privacy

  useEffect(() => {
    storePath(`legal-${type}`)
    document.title = `${active.title} | Enterprise Compute Central`
    window.scrollTo(0, 0)
  }, [storePath, type, active.title])

  return (
    <div className="ec-landing">
      <NavBar />

      <section className="sp-hero">
        <div className="sp-hero-inner">
          <div className="ec-hero-kicker">{active.kicker}</div>
          <h1>{active.title}</h1>
          <p>{active.desc}</p>
          <div style={{ fontSize: '0.8rem', color: 'var(--ec-muted)', fontWeight: 600 }}>Last Updated: {active.lastUpdated}</div>
        </div>
      </section>

      <section className="ec-section">
        <div className="sp-faq-list" style={{ maxWidth: '840px' }}>
          <div className="sp-faq-item" style={{ cursor: 'default', padding: '40px' }}>
            {active.fullContent ? (
              active.fullContent
            ) : (
              <div style={{ color: '#506055', lineHeight: 1.8, fontSize: '0.95rem' }}>
                <h3>1. Introduction</h3>
                <p>Welcome to Enterprise Compute. This {active.title} describes our practices regarding the information we collect through our platform and related services.</p>
                
                <h3 style={{ marginTop: '24px' }}>2. Scope of Service</h3>
                <p>Our platform provides comprehensive business operation tools including HR, Payroll, Accounting, and Inventory management. By using these services, you agree to the practices described in this document.</p>
                
                <h3 style={{ marginTop: '24px' }}>3. Data Collection & Usage</h3>
                <p>We collect information necessary to provide the services requested. This includes company profiles, employee records, and financial transaction data initiated by authorized users of your tenant workspace.</p>
                
                <h3 style={{ marginTop: '24px' }}>4. Security Measures</h3>
                <p>We implement enterprise-grade security protocols, including data encryption at rest and in transit, to ensure the confidentiality and integrity of your business operations.</p>
                
                <h3 style={{ marginTop: '24px' }}>5. Contact Information</h3>
                <p>If you have any questions about our {active.title.toLowerCase()}, please contact our legal team at legal@epxcentral.com.</p>
              </div>
            )}
          </div>
        </div>
      </section>

      <Footer />
    </div>
  )
}

export default LegalPage
