// Content for the "Our Story" section on the About page, the same walkthrough
// published as the platform's detailed pitch document, told as one continuous
// story following one small business (and the sister business that joins it)
// through a single week, chapter by chapter through every module.
// Keep this in sync with the pitch document if either one changes.

const platformStoryContent = {
  intro: {
    kicker: 'Company and Product Overview',
    title: 'One system to run the business: sales, inventory, people, money, and an assistant that knows your real data.',
    lede: 'Amara has owned her three restaurants for six years, and she can tell you, to the naira, exactly what a bad week used to cost her. This is the story of one week that could have gone the same way, and didn’t.',
    paragraphs: [
      'Most growing businesses (retail chains, restaurants, hospitality operators, distributors, service companies) end up running on a patchwork of tools that don’t talk to each other: a point of sale system that has nothing to do with the accounting software, a separate payroll tool, a spreadsheet for inventory, and a bookkeeper who re-types everything into a ledger days or weeks after the fact. Sales happen in one system, stock moves in another, and the books catch up whenever someone finds the time. Amara ran her first restaurant that way for two years, and the one month it fell apart is the reason she went looking for something else.',
      'A large share of the world’s commerce also happens where the internet isn’t guaranteed: a busy retail floor, a warehouse with poor signal, a front desk during an outage. Most cloud based ERP and POS software simply stops working the moment the connection drops. For a business whose income depends on being able to sell, that’s a real risk to the day’s revenue, not a small inconvenience, and it’s the other reason Amara switched.',
      'Enterprise Compute Central is built around one decision that shapes everything else in it: every operational transaction, a sale, a purchase receipt, a stock adjustment, a payroll run, an asset purchase, works out and posts its own General Ledger entries the moment it happens. The books are never a separate job someone does later by hand; they are a direct, computed result of the business actually running.',
      'The platform is delivered as a modern, multi tenant, subscription web application, and, less common in this space, also as a full desktop application that keeps working with no internet at all. Both run the same modules, the same accounting engine, and the same permission model. What follows is one ordinary week at Amara’s business, told in full, with nothing about it smoothed over, because the ordinary week is exactly where a platform like this either earns its keep or doesn’t.',
    ],
    pillars: [
      { num: '01', title: 'One product, not five', body: 'Point of sale, inventory, purchasing, HR, payroll, and accounting are built as one system, not stitched together from separate ones.' },
      { num: '02', title: 'Real time, all the time', body: 'Every screen updates live as transactions happen, and every document posts its own ledger entries instantly, not on a delay.' },
      { num: '03', title: 'Keeps working offline', body: 'The desktop edition keeps selling with no internet at all, then syncs safely once the connection comes back.' },
      { num: '04', title: 'An assistant that knows your data', body: 'Epsilon understands each business’s own operational and financial data, not just general software questions.' },
      { num: '05', title: 'Books you can actually trust', body: 'Every posting is tied to one exact source document and can never be duplicated, so nothing gets counted twice or quietly lost.' },
      { num: '06', title: 'Access that matches the job', body: 'Fine grained permissions and approval steps mean people can do what their role needs, without an all or nothing admin switch.' },
      { num: '07', title: 'Watching for the obvious fraud', body: 'The same receipt number can’t quietly be used twice to claim two payments, the way it could on paper.' },
      { num: '08', title: 'Loads your data in, not just your logins', body: 'A product catalog or a week of attendance can be brought in from a spreadsheet in minutes, not typed in one row at a time.' },
    ],
  },

  chapters: [
    {
      id: 'dashboard',
      kicker: 'The Dashboard',
      title: 'The one screen that answers "how are we doing" honestly',
      lede: 'It is Monday, nine in the morning, and Amara opens her laptop before she has spoken to a single member of staff, before her coffee has even finished dripping.',
      paragraphs: [
        'The dashboard is already waiting for her, the first screen anyone at the business sees on logging in, and one every single employee gets for free, whether or not the business has paid for any other module yet. The weekend’s revenue is already sitting on the screen, next to cost of goods sold, gross profit, total expenses, and net profit, the small handful of key performance indicators that answer "how are we doing" at a glance, pulled together from every operational corner of the business at once.',
        'Amara has been burned before by a dashboard that told her one story while her accountant’s real reports told her another, an entire quarter at her first restaurant where the "numbers looked fine" right up until they very much weren’t, so before she trusts anything on this screen, she checks it against the Profit and Loss statement for the same period, out of old habit more than real doubt at this point. The numbers match, exactly, the way they always do now. That is not a coincidence. The dashboard’s revenue, cost, and profit figures are pulled from the very same accounting engine that produces the official report, on purpose, specifically so the two screens can never quietly drift apart from each other.',
        'She scrolls down. Her busiest restaurant shows a stock warning: a popular product is running low there specifically. She also notices a till session from Sunday night still shows as open, which is either a very late cashier or, more likely, someone who forgot on their way out the door. Further down, the dashboard shows which products are moving the most, which are earning the most, and a running mix of where revenue is really coming from.',
        'While she is still looking at the screen, a sale happens at one of her other locations. She does not refresh the page; the number simply updates, wired into the same real time connection that keeps every other screen current, which still, six years in, gives her a small private thrill she’d never admit to her staff.',
        'Two things on that one screen are bothering her now, a stuck session and a low stock warning, both at the same restaurant. She grabs her keys.',
      ],
      whyMatters: 'For a business owner, this is the difference between a dashboard that is a nice looking summary and one that is an honest, live reflection of the actual business, provably consistent with the real books behind it.',
      bridge: 'By the time Amara pulls into the car park, the lunch rush has already started, and one of her cashiers is having a morning that started long before Amara arrived.',
    },
    {
      id: 'sales-pos',
      kicker: 'Point of Sale, Sales and Delivery',
      title: 'Where the money actually changes hands',
      lede: 'Amara walks in to find Tola, one of her longest serving cashiers, mid-sentence in what is clearly not the first time she has told this story this morning.',
      paragraphs: [
        '"It was NOT a slow night," Tola says, with the specific outrage of someone who has been blamed for something and knows exactly who to blame back, which turns out to be the weather, the wifi, and, briefly, a customer who ordered four separate times "just to be difficult." She opened her till on Friday with a cash count, the way she does every shift. She does not have permission to see what other cashiers were doing that night, only her own session, because Amara set her access up that way from the start, a fact Tola has complained about exactly once and then quietly stopped complaining about, since it also means nobody can see her sessions either. What she could do was ring sales fast, including a table’s order split across a card and a cash payment, each part quietly mapped to the right account behind the scenes. Then, at half past seven, the internet dropped.',
        'Tola had not even noticed anything was wrong, which is either a compliment to the system or an indictment of how much attention she was paying to anything but the till. It kept taking orders exactly as before, because a sale is queued the instant it is rung up whether or not the connection is there to send it anywhere. Forty minutes later, everything she had rung up during the outage synced on its own. Because each sale carries its own fingerprint, a sale her screen retried sending twice was recognized as the same sale and quietly discarded rather than counted again, which is the one part of Friday night nobody had to argue about afterward.',
        'Every one of those sales, instant or delayed, had already written its own correct accounting entry the moment it was saved: revenue credited, each payment method debited correctly, and any unpaid portion booked straight to the customer’s running balance.',
        'At half past ten, a delivery rider finally dropped off an order that had left the kitchen forty minutes earlier, blaming a gate that was locked for reasons nobody at the restaurant has ever been able to explain. Until that moment, that sale was only a promise of revenue, not real revenue, because delivery is simply a status on the very same sale, and revenue only counts the instant that status flips to delivered.',
        'Then came the part Tola was really building up to. A regular customer, the kind who tips well and orders the same thing every time, came in Saturday to settle a debt from two weeks back, receipt in hand. Tola went to record the recovery, and the system stopped her cold: that exact receipt number had already been used, at that same payment point, the week before. Tola hadn’t noticed. The customer, when gently pressed, suddenly remembered he’d "found the old one in his other jacket" and produced a different receipt entirely. Whether it was an honest mix-up or a man betting nobody would check twice, the platform checks the same way either time: a receipt is compared against every other receipt already recorded at that payment point, and a repeat gets stopped before it becomes a second payment for money that was already collected once. It is not a lock nobody can ever get past with the right clearance, and it will not chase down a truly determined liar with a story for every jacket he owns, but it catches the ordinary version of this, the one that actually happens, before it costs the business anything.',
        'And because the shortage was not written off. Tola closed her session and came up short by an amount that did not immediately make sense, and, for one deeply uncomfortable minute, tried out three different theories before settling on "I genuinely do not know." It did not matter. The shortage was recorded, categorized, and attributed specifically to Tola’s session, so both she and her manager knew exactly what was unaccounted for before she left for the night. In the weeks ahead, as she pays part back in cash and grumbles about the rest coming out of her pay, both recoveries are tracked against that exact original shortage, never counted as a fresh sale, and never, as she’d hoped, quietly forgotten about.',
        'Amara mentions, almost in passing, that her sister Ifeoma runs her small hotel a similar way, except once a month rather than once a shift, since a lounge two doors down from Ifeoma’s front desk works out exactly what each regular still owes for the use of its shisha area, carrying forward what was not paid last month, recorded together in one step.',
      ],
      whyMatters: 'For a business owner, this is the difference between finding out how a chaotic night actually went the next day, from a spreadsheet, and knowing it the moment the last till closes, correct to the naira, with the one obvious kind of fraud already caught on the way in.',
      bridge: 'Satisfied that Friday’s chaos is fully accounted for, and privately relieved the receipt thing turned out to be nothing, Amara turns to the real reason a popular product ran low here in the first place, and picks up her phone to call Chidi, who runs her warehouse across town.',
    },
    {
      id: 'inventory',
      kicker: 'Inventory, Warehousing and Production',
      title: 'Knowing exactly what you have, right now',
      lede: 'Chidi, who runs the warehouse that feeds all three of Amara’s restaurants, is still on the phone with her about Friday’s shortage when a second call comes in, a corporate customer asking whether there are 200 bags of rice in stock, right now.',
      paragraphs: [
        'He gives the customer a real answer, not a guess. There is no separate "current stock" figure sitting on a product that could have drifted out of step with reality. Every receipt, sale, transfer, damage, and production movement is its own transaction record, and the figure on Chidi’s screen is simply the sum of every one of those records at the moment he looks. He has said this same sentence to Amara often enough that she can now recite it back to him, usually right before he does.',
        'Back on the line with Amara, Chidi agrees to send fifty cases to her main road restaurant. He cannot just wave them through, tempting as it is with a queue of other problems waiting. He raises a transfer request, and it sits there until whoever the business has designated to approve transfers clears it. Chidi grumbles, half-seriously, that he could just move the boxes himself and sort out the paperwork later, the way he used to at his old job, right up until the one time that "later" turned into two warehouses disagreeing for a month about who actually had forty sacks of onions. He does not do that here. This is the one place on the entire platform where that approval is checked a second time, independently, by the server itself, inside the same all or nothing operation that physically moves the stock, so the same approved transfer can never be posted twice even if two people try to finalize it in the same instant.',
        'Later that week, a team counts the warehouse shelf by shelf. The count does not match what the system expects. Chidi gets a full breakdown: opening quantity, every movement since, and the actual gap in both quantity and cost. Recording the count is one step; deciding whether to adjust the books or treat it as a real shortage is a separate, deliberate decision, and not the same thing as the ordinary Adjustments screen he uses most weeks, which is simply where opening stock gets entered when a new product line starts, or where a case of tomatoes that split open in the back of a delivery truck gets written off as damage, a manual, everyday correction rather than something that came out of a physical count. When the shelf count genuinely turns up a shortage, it becomes a real balance owed by the staff responsible, recoverable gradually through cash or a payroll deduction, and this week it lands, not entirely to Chidi’s surprise, on the same new hire who also can’t seem to find the stapler.',
        'That evening, the bakery attached to the main road restaurant turns flour and sugar into two hundred loaves of bread. The system checks every ingredient is available before allowing the run, values what went in at its real average cost, and spreads that cost across what came out, with any genuine difference booked as its own variance line rather than hidden. It is, Chidi will tell anyone who asks, the least dramatic part of his entire week, which is exactly how he likes his bread and his ledgers both.',
        'Hanging up with Amara at last, Chidi notices something else: the flour and sugar he just used tonight have not been reordered in weeks.',
      ],
      whyMatters: 'The warehouse transfer’s independent server side check is a concrete example of the platform doing the hard, careful thing in exactly the one place where a race between two people, or one impatient shortcut, would otherwise cause real financial damage.',
      bridge: 'First thing the next morning, a supplier’s truck pulls up outside Chidi’s warehouse anyway, on schedule, with exactly the flour and sugar he was about to go looking for.',
    },
    {
      id: 'purchasing',
      kicker: 'Purchasing, Customers and Vendors',
      title: 'One real record behind every purchase, and a real ledger behind every relationship',
      lede: 'The supplier’s truck that pulls up outside Chidi’s warehouse the next morning unloads forty cartons of flour and sugar. The invoice for them will not arrive for another week, which the supplier’s driver announces with the breezy confidence of a man who has said this exact sentence every week for three years.',
      paragraphs: [
        'Chidi’s team receives the delivery anyway, because receiving and pricing are genuinely two different jobs. What gets created is one real purchase record, not three separate documents that could disagree, moving through a clear stage: raised, then received, printable at any point as a plain purchase order, a quantity only goods received note, or, once payment starts, a full invoice. Receiving is posted inside one all or nothing operation together with the matching stock movement.',
        'That same week, Amara’s business also pays its landlord for the warehouse, a cost that has nothing to do with cartons at all. That runs through a second, separate path, a vendor bill, posting straight to what is owed without inventing a fake inventory item.',
        'Because a supplier can be set up with its own dedicated account, the business also runs a built in check, on demand, comparing that supplier’s own running balance against what the ledger itself shows, catching the kind of quiet mismatch that would otherwise only surface during an audit, the way it did once, memorably and expensively, at a supplier Amara no longer uses.',
        'On the other side of the same business, a corporate customer, the one who called Chidi about the rice, has turned her question into a formal order about to become an invoice. Every customer and vendor carries a real, drillable ledger, with an aging report that sorts what is owed by exactly how overdue it is, current, 30, 60, 90 days and beyond.',
        'Before Chidi even thinks to ask what needs reordering next, a suggestion is already waiting for him, built from the same reorder calculation that powers Amara’s dashboard, so the two can never disagree, which is one less argument for the two of them to have this month.',
        'Word of how smoothly all of this runs has already travelled further than Chidi’s warehouse. Amara’s sister Ifeoma, who runs a small hotel two streets from the main road restaurant, has finally decided to move her own business onto the same platform, partly out of genuine interest and partly, she will admit, because she is tired of Amara mentioning it at every single family dinner.',
      ],
      whyMatters: 'The built in reconciliation check is a good example of engineering discipline: rather than assuming a computed balance can never drift, the platform ships a way to independently verify it.',
      bridge: 'Getting her hotel’s room list and minibar items into the new system turns out to be Ifeoma’s very first job on the platform, and her first real test arrives before she has even finished it.',
    },
    {
      id: 'accommodations',
      kicker: 'Accommodations',
      title: 'Room and stay billing, done properly',
      lede: 'Rather than type in every room, every toiletry, and every minibar item one at a time, Ifeoma downloads a blank spreadsheet template from the system, fills in her whole catalog in one afternoon, and uploads it back, mapping her own column headers to the right fields once so the import knows which column is the name and which is the price.',
      paragraphs: [
        'It is, she tells Amara on the phone, the single least glamorous thing she has ever felt genuinely pleased about. Two hours of typing instead of two days of it, and every item she needs already sitting in the system before her first real guest even checks in.',
        'That guest turns out to be a family booking three rooms for a wedding weekend, and Ifeoma’s new front desk software gets its first real test almost immediately. The instant her receptionist saves the booking, guest, dates, arrival and departure times, and all three rooms together, the full charge is already booked, both to revenue and to the family’s running balance.',
        'On Friday night the family pays half in cash. On Saturday, more by transfer. On Sunday, the last payment slightly overshoots the balance because they round up, and for one heart-stopping second Ifeoma is convinced the system has made an arithmetic error in the family’s favor. It hasn’t. Her receptionist does not have to keep a running tally in her head; the balance still owed is always worked out fresh from the complete payment history, and the small overpayment is booked as a deposit owed back, never forced into an impossible negative debt.',
        'On Saturday evening, the same family also runs a bar tab, unrelated to their rooms, ordering, among other things, four separate rounds of the same cocktail that a groomsman insists on calling by the wrong name all night. That runs through the same Point of Sale workflow Tola relies on across town, its own separate process. What connects the two is a shared ledger and shared reports, so by Monday Ifeoma sees one true financial picture even though rooms and bar tab were recorded through two different, purpose built paths.',
        'Ifeoma remembers Amara mentioning something similar but not identical, a lounge near her own hotel that bills its regulars a fixed monthly charge for the use of a space rather than a guest stay, a Sales and Point of Sale feature, not Accommodations, a distinction she is fairly sure she will still be explaining to her own staff a year from now.',
      ],
      whyMatters: 'Every kind of charge, however it is structured, resolves into the same real, computed ledger, rather than a bolt on spreadsheet sitting next to the accounting system.',
      bridge: 'On the phone with Amara that evening, riding the high of a wedding weekend that went right, Ifeoma half jokes that between her hotel and the restaurants, the two of them really ought to just buy a van.',
    },
    {
      id: 'assets-expenses',
      kicker: 'Fixed Assets and Operating Expenses',
      title: 'Everything a business owns and spends, accounted for properly',
      lede: 'Ifeoma’s half joke turns out not to be a joke at all. By Tuesday, Amara has actually gone and bought a delivery van, a decision that takes considerably less time than the argument that follows over what color to paint it.',
      paragraphs: [
        'The same afternoon, one of her drivers pays for a tank of fuel out of his own pocket and asks to be paid back, producing a receipt so crumpled it takes two people to read the total on it. Both are real money leaving the business, but nothing alike. The van gets recorded as a draft first: its cost, expected useful life, and how it should depreciate, spreading its cost across the years it is actually used rather than treating the whole purchase as one expense on day one. Amara chooses straight line, an equal amount written off every period, over reducing balance or no depreciation at all.',
        'A year later, one depreciation period will already be posted and will stay posted, never silently recalculated, and the platform will not let the same period post twice. Years after that, disposal will work out the real gain or loss against what the van was actually still worth on the books, and once disposed, it cannot be disposed of again, which is one argument, at least, that this particular van will never be part of.',
        'The driver’s fuel receipt, crumples and all, is settled that same afternoon as a single, straightforward record, category, amount, how it was paid, posted the moment it is saved, landing in whichever account the category maps to.',
        'By the end of the week, between the shortage, the transfer, the flour and sugar delivery, the vendor bill, the wedding party’s payments, and now a van and a fuel receipt, Amara’s accountant has a genuinely busy month to close out properly, and does not yet know about the van’s color, which is for the best.',
      ],
      whyMatters: 'Assets get the careful, stateful life cycle a real asset register needs, while routine expenses stay simple and fast.',
      bridge: 'At month end, all of it lands on the desk of Uche, the accountant who has kept Amara’s books straight since her very first restaurant opened, and who has strong, specific opinions about crumpled receipts.',
    },
    {
      id: 'accounting',
      kicker: 'Accounting and the General Ledger Engine',
      title: 'The part everything else is really built around',
      lede: 'Uche sits down at month end to prepare the Trial Balance, and this month has not been a quiet one.',
      paragraphs: [
        'In just the last few weeks, this business took sales through a power cut, moved fifty cases between two locations, found a real shortage, caught a reused receipt before it cost anyone anything, turned flour and sugar into bread, received forty cartons before the invoice arrived, paid a vendor bill for rent, and bought a delivery van. None of those events were left waiting to be turned into accounting entries after the fact. Every one had its own dedicated logic work out exactly which accounts should move, the instant it happened, always as a balanced debit and credit pair.',
        'Uche’s next worry, out of long habit, is whether any of that got counted twice, especially the sale during Friday’s power cut. It did not. Every automatic posting is tied to the exact source event that produced it, so a retried request during that outage is recognized as the one already posted, never a duplicate. He checks anyway, the way he always does, and for about four seconds genuinely believes he has found a problem before realizing he is looking at last month’s tab.',
        'The Trial Balance is not recomputed from the beginning of history every time. Each month end, a snapshot of every account’s balance is built forward from the month before. Once Uche is satisfied a month is settled, he can lock it, blocking any new posting on or before that date. If something later turns up that would have changed an already closed month, the platform flags it for review automatically, which has saved him, by his own count, at least one holiday.',
        'The Trial Balance, Balance Sheet, and Profit and Loss statement are all built from the same real ledger entries, with every balance drilling straight down to the individual postings behind it, Friday’s sale, the transfer, the van, each one findable, each one exactly where he expects it to be, which is the closest thing Uche has to a hobby.',
        'Uche closes the month satisfied, but one thing is still outstanding: payday for everyone at the business, including Tola, is due any day now.',
      ],
      whyMatters: 'This computed ledger approach removes, by construction, the usual integration burden between a point of sale system and an accounting package.',
      bridge: 'With the books closed, it is finally time for Ngozi, who runs payroll for the business, to work out exactly what everyone is owed.',
    },
    {
      id: 'payroll',
      kicker: 'People, Attendance and Payroll',
      title: 'Paying people correctly, every time, without a separate spreadsheet',
      lede: 'Payday is tomorrow, and Ngozi starts, as she does every period, by pulling the week’s attendance off the fingerprint clock at the main road restaurant, the same battered little device that has been recording who showed up and when since long before this platform existed.',
      paragraphs: [
        'She exports it as a spreadsheet, the way she always has, uploads it, and, because she set this up once months ago, the system already knows which column is the employee ID and which is the hours worked; it matches every row to the right person automatically from there. The first time she did this, she spent a confused twenty minutes before realizing she had the ID and duration columns swapped, and every employee appeared to have worked either zero hours or several thousand. She has not made that mistake since, mostly out of sheer terror of doing it again in front of Amara.',
        'From that attendance batch, three people on Ngozi’s list are not going to be simple this period. Tola is still working off the shortage from Friday night. Chidi is owed a bonus for a genuinely difficult week. A third employee missed four days, for reasons he describes, at length and with visual aids, as "a whole situation" that Ngozi has decided not to ask further questions about. She enters everything the period needs to account for, all recorded per employee, in one place, rather than scattered across an attendance sheet, an IOU notebook, and a shortage list.',
        'From that one batch, the platform works out exactly what each person is owed. Gross pay comes from salary and attendance together; total deductions are added up separately. For Tola, net pay can never be pushed below zero, because recovery is always capped at that period’s gross pay; whatever is still outstanding carries forward to the next period rather than the business clawing back more than she earned. What is recovered is split proportionally across debt, shortage, and any penalty, so the books always add up to exactly what was deducted, a fact Tola finds only slightly comforting when she sees the number on her payslip.',
        'By the time Ngozi is done, payslips are ready for everyone, and an appointment letter for a new hire, all carrying the business’s real name, address, and logo, pulled live from the company’s own profile. The shortage recovered through Tola’s deduction lands in precisely the same account a direct cash recovery would have, so it is never counted twice.',
      ],
      whyMatters: 'This turns payroll from a monthly exercise in cross referencing three separate lists into one connected calculation that is correct the first time, for every employee.',
      bridge: 'That night, back at the restaurant, payslip freshly received and not entirely happy about it, Tola opens Epsilon on her phone with one question on her mind: whether there is any way to make that deduction go away.',
    },
    {
      id: 'epsilon',
      kicker: 'Epsilon, the Built in Assistant',
      title: 'An assistant that actually knows the business it is talking about',
      lede: 'Tola asks Epsilon, out loud, using her voice, exactly what was taken out of her pay this month, in a tone that suggests she is hoping for a different answer than the one she already knows is coming.',
      paragraphs: [
        'Epsilon supports genuine two way conversation, including a hands free mode built for someone standing at a counter rather than a keyboard, with both listening and speaking happening entirely inside her own browser; no audio is ever sent anywhere. But this particular question, it tells her plainly, it cannot answer for her directly. Payroll figures and personal debt are restricted to admin access, even through Epsilon, and it says so honestly, pointing her to her manager or Ngozi instead, which is not the loophole Tola was quietly hoping for, and she tells it as much.',
        'What it can help with is the till that will not close properly, a smaller, more solvable problem she has actually been having for a week. Epsilon has real, grounded knowledge of both how the platform works and, within her own access, the business’s real data, so it diagnoses her actual problem directly, no closer to fixing her payroll deduction, but at least her evening is now shorter by ten minutes of button-mashing.',
        'Across town, Chidi has been meaning to sit down and work out next month’s reorder. Epsilon can already propose the real action itself, a draft purchase order, vendor matched, priced, and dated, shown as an editable card he can adjust before deciding anything. He runs it, and it becomes a real purchase record. Nothing happens on its own; Epsilon proposes, a person confirms, a distinction Chidi is quietly grateful for after the transfer conversation earlier in the week.',
        'Amara, checking in before bed, asks Epsilon for this month’s report and gets back one of the platform’s own real reports, generated on demand, in the same shape the report screens themselves produce.',
        'Every conversation is billed on real, metered usage, converted transparently into the business’s own balance, never a flat allowance that quietly erodes as usage grows. A faster, cheaper model answers simple turns like Tola’s, and the platform only calls in a stronger model for turns that genuinely need one, like drafting Chidi’s purchase order. The platform’s own operators can see real margin, what was actually spent against what was actually charged, tenant by tenant.',
      ],
      quote: 'Epsilon exists to answer the two questions every operator ends up asking all day: how do I do this, and what does my own business’s data actually say right now, without waiting on a manual, a training session, or a report that is already a day old.',
      whyMatters: 'Epsilon is a second, genuine revenue line with real, computed margin, and a capability, drafting a real purchase order for a human to confirm, that most competitors in this space are not built to match without starting over.',
      bridge: 'What strikes Tola most, closing her phone for the night still faintly annoyed, is that the one question it would not touch, her own pay, was the same question that stayed carefully guarded everywhere else on the platform too. That line did not draw itself.',
    },
    {
      id: 'security',
      kicker: 'Security, Access and How the Platform is Put Together',
      title: 'Control, trust, and the architecture underneath it',
      lede: 'It is Friday evening, one week after the night that started all of this, and Amara sits down to make sense of everything that just happened, and everything that let it happen safely.',
      paragraphs: [
        'She thinks first about Tola, who could ring a sale and close her own till, but never had access to see what any other cashier was doing, and who tried, not especially subtly, to get Epsilon to hand over payroll figures it was never going to give her. An admin chooses from a large, specific set of individually assignable rights, close to sixty of them, covering module access, everyday actions, and approval authority. Amara gave her store managers exactly the one right that matters for their jobs, and nothing that touches payroll at all.',
        'She thinks about the receipt Tola almost recorded twice, and the reused receipt number the system caught before it became a second payment for money already collected once. It is not an unbreakable lock, and she knows it, but it is watching for the exact ordinary way this kind of thing actually happens, which is more than her old spreadsheet ever did.',
        'She thinks next about Ifeoma. Her hotel runs on the exact same servers and database software as Amara’s restaurants, yet the two businesses could never see a naira of each other’s money. Each business, or tenant, runs in its own real, separate database, selected the moment a request arrives from which business’s address it came in on, with every login cross checked against that same business on every request.',
        'A few specific things could never be quietly abused, even by someone inside the business. Nobody but an admin can change a person’s login status or permissions, even on their own account. Nobody but an admin can restructure the chart of accounts. The number of people allowed to use Epsilon is capped the moment access would actually be switched on for someone.',
        'She thinks about Chidi’s warehouse transfer, the one safeguard on the whole platform built to survive a genuine race between two people, checked a second time by the server itself inside the same operation that moves the stock, and about how close he came to just moving the boxes himself out of impatience.',
        'She thinks about the month Uche just closed and locked, about the internet outage at the main road restaurant that barely mattered because the platform runs both as a cloud application and a full offline desktop application on the same modules and engine, and about the separate, internal console, reachable by nobody at any customer business, where the platform’s own operators manage tenants like Ifeoma’s hotel, subscriptions, and Epsilon seats.',
        'Satisfied, Amara opens her laptop one more time and pulls up the dashboard, the very first screen this whole week began with. This time, every number on it already makes sense, including, she notices with a small private laugh, the delivery van, which is apparently going to be red.',
      ],
      whyMatters: 'A real per tenant database, a real session revocation model, and a real transactional safeguard on the one workflow where a race condition would cause actual financial damage are concrete evidence of engineering maturity, not a line on a slide.',
      bridge: 'Amara’s week, and her sister’s, is one small, real example of what this platform is built to do.',
    },
  ],

  closing: {
    kicker: 'Why It Matters',
    title: 'Why a business adopts it',
    table: {
      headers: ['Without Enterprise Compute Central', 'With Enterprise Compute Central'],
      rows: [
        ['Point of sale, inventory, payroll, and accounting are separate tools that have to be reconciled by hand.', 'One system; every transaction posts its own correct ledger entries the instant it happens.'],
        ['Financial reports are only as current as the last manual bookkeeping pass.', 'Trial Balance, Balance Sheet, and Profit and Loss are computed from real, current ledger entries, with drill down to every posting.'],
        ['An internet outage stops the till.', 'Sales keep being taken straight through a network outage and sync safely once reconnected.'],
        ['A reused receipt can quietly pay out the same debt twice.', 'The same receipt number at the same payment point is caught before it becomes a second payment.'],
        ['Loading a product catalog or a week of attendance means typing every row in by hand.', 'A spreadsheet upload, mapped once, brings a whole catalog or attendance batch in at once.'],
        ['Routine access decisions bottleneck on a single admin.', 'A large, specific set of assignable rights lets staff do exactly what their role requires.'],
        ['New staff need training material and a manual for basic questions.', 'Epsilon answers instantly, grounded in the platform’s real documentation and the tenant’s own data.'],
      ],
    },
  },
}

export default platformStoryContent
