/* ============================================================================
   Industry content for /industries and /industries/:slug.
   ----------------------------------------------------------------------------
   Each entry is written against what the platform can genuinely do for that
   sector — the `modules` array lists real module slugs from content/products.js
   (which in turn match moduleCatalog.js), so an industry page can never
   promise a capability that does not ship.

   The sector list leans towards the operator-led, multi-site, cash-handling
   businesses this platform is actually built for, rather than mirroring the
   enterprise-only sector lists used by the large vendors.
   ========================================================================= */

export const INDUSTRY_GROUPS = [
  { key: 'retail', name: 'Retail & consumer' },
  { key: 'hospitality', name: 'Hospitality & services' },
  { key: 'industrial', name: 'Industry & field' },
  { key: 'care', name: 'Care & public' },
]

export const INDUSTRIES = [
  /* ------------------------------------------------------- retail group -- */
  {
    slug: 'retail',
    group: 'retail',
    name: 'Retail & multi-store',
    eyebrow: 'Retail',
    title: 'Run every till, every shelf and every branch from one system',
    summary: 'Fast tills that work offline, stock that matches the shelf, and a daily cash-up you can actually trust.',
    lede: 'Retail fails quietly: a till that is slow at the busiest hour, a shelf that says eleven when there are four, a drawer that is short and nobody knows whose shift it was. Enterprise Compute closes all three gaps with one record of what was sold, what moved and who was on.',
    heroImage: 'supermarketShopping',
    cardImage: 'retailStore',
    challenges: [
      { title: 'The count never matches the shelf', text: 'Every sale, transfer, return and wastage is a recorded movement, so a variance has a cause you can open rather than a number you write off.' },
      { title: 'Queues when the network drops', text: 'The till keeps selling offline against its local stock copy and reconciles automatically on reconnect.' },
      { title: 'Cash shortfalls with no owner', text: 'Session-based cash handling ties the float, the sales and the closing count to a named operator and shift.' },
      { title: 'Branches reporting different numbers', text: 'Each branch posts to one chart of accounts, so group and per-branch figures come from the same ledger.' },
    ],
    capabilities: [
      'Multi-till, multi-branch POS with per-session cash accountability',
      'Stock position per location, with transfers tracked in transit',
      'Reorder thresholds surfaced before the shelf empties',
      'Discount and void as separate permissions from selling',
      'Daily revenue, margin and shrinkage visible on the dashboard',
      'Customer accounts with credit limits enforced at the till',
    ],
    modules: ['pos', 'inventory', 'sales', 'journals', 'reports', 'employees'],
    facts: [
      { value: 'Offline', label: 'Trading continues through network outages' },
      { value: 'Per shift', label: 'Cash variance attributed to an operator' },
      { value: 'Per branch', label: 'Stock, revenue and margin, consolidated or separate' },
    ],
    quote: {
      text: 'We used to close the shop to count stock. Now the count is a check on a number we already have, not a discovery exercise.',
      name: 'Adaeze O.',
      role: 'Operations Lead',
      company: 'three-branch grocery retailer',
      avatar: 'portraitWoman1',
    },
    faqs: [
      { q: 'Can I run several shops on one workspace?', a: 'Yes. Locations are a first-class concept: each holds its own stock position and cash sessions, while the ledger and reporting consolidate across them.' },
      { q: 'What happens during a power or network cut?', a: 'The till continues selling against its local copy. When connectivity returns the queued sales replay in order, stock reconciles and the dashboard catches up.' },
    ],
  },
  {
    slug: 'distribution',
    group: 'retail',
    name: 'Wholesale & distribution',
    eyebrow: 'Wholesale & distribution',
    title: 'Trade pricing, credit control and fulfilment that hold together',
    summary: 'Customer-specific pricing, enforced credit limits, dispatch tracking and payables you can see, built for businesses that move volume on terms.',
    lede: 'Distribution runs on margin measured in single digits and credit extended on trust. The two things that kill it are selling below cost without noticing and extending credit nobody is tracking. Both are structural problems, and both have structural answers here.',
    heroImage: 'warehouseLogistics',
    cardImage: 'warehouseForklift',
    challenges: [
      { title: 'Different prices for different customers', text: 'Price lists and customer-specific pricing applied automatically, with discount limits enforced by permission rather than by memory.' },
      { title: 'Credit extended beyond what is safe', text: 'Credit limits and terms per partner, checked at the point of order, with ageing visible on the partner account.' },
      { title: 'Margin eroded by landed cost', text: 'Freight, duty and handling attributed to the goods they relate to, so item cost reflects what the stock actually cost to land.' },
      { title: 'Deliveries and collections unreconciled', text: 'Dispatch, proof of delivery and cash-on-delivery reconciliation by rider and by run.' },
    ],
    capabilities: [
      'Customer price lists with permission-bound discounting',
      'Credit limits enforced at order entry, with ageing per partner',
      'Landed cost attribution so margin reflects reality',
      'Purchase order, goods receipt and invoice three-way matching',
      'Dispatch, proof of delivery and cash reconciliation per run',
      'Payables and receivables kept in step with the ledger',
    ],
    modules: ['inventory', 'sales', 'purchase', 'delivery', 'business-partners', 'reports'],
    facts: [
      { value: '3-way', label: 'Matching across order, receipt and invoice' },
      { value: 'Enforced', label: 'Credit limits applied before the order is taken' },
      { value: 'Landed', label: 'Cost attribution so margin is real' },
    ],
    quote: {
      text: 'The ageing report changed how we sell. We stopped shipping to accounts that were ninety days out because now we actually see it at the point of order.',
      name: 'Samuel A.',
      role: 'Commercial Director',
      company: 'FMCG distributor',
      avatar: 'portraitMan2',
    },
    faqs: [
      { q: 'Can one business be both a customer and a supplier?', a: 'Yes. A single partner record can carry both a receivable and a payable position, which is normal in distribution.' },
    ],
  },
  {
    slug: 'pharmacy',
    group: 'retail',
    name: 'Pharmacy & health retail',
    eyebrow: 'Pharmacy',
    title: 'Controlled stock, expiry visibility and a dispensing counter that moves',
    summary: 'Item-level stock control with expiry awareness, restricted-line permissions and a till that keeps serving when the line is long.',
    lede: 'A pharmacy carries thousands of lines, many of them expensive, some of them restricted and most of them dated. The stock problem is not quantity, it is knowing which specific units you hold and when they stop being sellable.',
    heroImage: 'pharmacy',
    cardImage: 'pharmacist',
    challenges: [
      { title: 'Stock that expires on the shelf', text: 'Item-level movement history and reorder thresholds mean slow-moving dated lines are visible before they are written off.' },
      { title: 'High-value shrinkage', text: 'Every movement is attributed, and adjustments require a recorded reason, so loss is investigated rather than absorbed.' },
      { title: 'Restricted lines sold by the wrong person', text: 'Permissions are per action, so handling restricted lines can be limited to specific staff without taking them off the counter.' },
      { title: 'Margin invisible across thousands of lines', text: 'Margin by item and by category computed from real cost and real selling price, not an assumed markup.' },
    ],
    capabilities: [
      'Thousands of items with per-location stock positions',
      'Reorder thresholds and slow-mover visibility',
      'Permission-restricted handling for controlled lines',
      'Attributed adjustments with mandatory reason codes',
      'Margin by item and by category from posted figures',
      'Fast counter POS with multiple payment methods',
    ],
    modules: ['pos', 'inventory', 'purchase', 'sales', 'reports', 'employees'],
    facts: [
      { value: 'Item level', label: 'Movement history on every line you carry' },
      { value: 'Per action', label: 'Permissions for restricted handling' },
      { value: 'Real', label: 'Margin from actual cost, not assumed markup' },
    ],
    quote: {
      text: 'Write-offs used to be a monthly surprise. Now we see slow movers early enough to actually do something about them.',
      name: 'Chinwe E.',
      role: 'Superintendent Pharmacist',
      company: 'community pharmacy group',
      avatar: 'portraitWoman4',
    },
    faqs: [
      { q: 'Does it handle batch and expiry?', a: 'Stock is tracked per item per location with full movement history, and reorder and slow-mover signals surface dated lines early. Batch-level attributes are handled through item configuration.' },
    ],
  },
  {
    slug: 'fuel',
    group: 'retail',
    name: 'Fuel & forecourt',
    eyebrow: 'Fuel & forecourt',
    title: 'Pump sales, shift accountability and shrinkage you can see',
    summary: 'Shift-based cash handling, volume reconciliation and a shop that runs on the same system as the forecourt.',
    lede: 'Forecourts lose money in two places: the drawer and the tank. Both are shift problems. When every litre sold and every naira taken belongs to a named shift, the variance stops being a cost of doing business.',
    heroImage: 'fuelStation',
    cardImage: 'fuelPump',
    challenges: [
      { title: 'Cash variance with no owner', text: 'Session-based handling ties the opening float, the sales and the closing count to the attendant and the shift.' },
      { title: 'Volume dispensed versus volume sold', text: 'Recorded sales give you the figure to reconcile dispensed volume against, so a gap is measurable rather than suspected.' },
      { title: 'The shop and the pumps on separate systems', text: 'Forecourt and convenience sales run through the same POS, the same stock and the same ledger.' },
      { title: 'Credit customers and fleet accounts', text: 'Fleet and account customers tracked as partners with credit limits and statements.' },
    ],
    capabilities: [
      'Shift sessions with declared float and closing count',
      'Convenience shop stock and forecourt sales in one system',
      'Fleet and account customers with enforced credit limits',
      'Attendant-level accountability on every session',
      'Daily revenue and variance on the dashboard',
      'Offline operation through power and network interruptions',
    ],
    modules: ['pos', 'inventory', 'sales', 'business-partners', 'employees', 'reports'],
    facts: [
      { value: 'Per shift', label: 'Cash accountability by named attendant' },
      { value: 'One system', label: 'Forecourt and convenience shop together' },
      { value: 'Offline', label: 'Keeps selling through interruptions' },
    ],
    quote: {
      text: 'Shift variance went from an argument to a number on a screen with a name next to it. That alone changed behaviour.',
      name: 'Tunde B.',
      role: 'Station Manager',
      company: 'independent fuel retailer',
      avatar: 'portraitMan4',
    },
    faqs: [
      { q: 'Does it integrate with pump controllers?', a: 'Sales are recorded through the POS and reconciled against dispensed volume. Direct controller integration is handled case by case through the integrations programme.' },
    ],
  },

  /* -------------------------------------------------- hospitality group -- */
  {
    slug: 'restaurants',
    group: 'hospitality',
    name: 'Restaurants & QSR',
    eyebrow: 'Restaurants',
    title: 'Tables, kitchen and delivery, without three separate systems',
    summary: 'Order flow from table to kitchen to bill, with recipe-level stock consumption and delivery reconciliation.',
    lede: 'A restaurant is a manufacturer that also runs a shop. Food comes in as ingredients and leaves as dishes, and unless the system understands that conversion, food cost is a guess and waste is invisible.',
    heroImage: 'restaurantKitchen',
    cardImage: 'restaurantService',
    challenges: [
      { title: 'Food cost nobody can calculate', text: 'Production and assembly consume components and produce finished items, so the cost of a dish is derived from real ingredient cost.' },
      { title: 'Orders lost between floor and kitchen', text: 'One order record drives the customer bill and the kitchen ticket, with distinct receipt layouts for each.' },
      { title: 'Delivery cash that does not come back', text: 'Dispatch, proof of delivery and per-rider cash reconciliation on every run.' },
      { title: 'Wastage absorbed silently', text: 'Wastage is a recorded movement with a reason, so it appears in the figures instead of inside a stock variance.' },
    ],
    capabilities: [
      'Table management, takeaway and delivery in one order flow',
      'Kitchen and customer receipt variants from the same order',
      'Recipe-level consumption via production and assembly',
      'Wastage recorded as an attributed movement',
      'Per-rider delivery cash reconciliation',
      'Multi-outlet stock and revenue consolidation',
    ],
    modules: ['pos', 'inventory', 'sales', 'delivery', 'employees', 'reports'],
    facts: [
      { value: 'Recipe level', label: 'Ingredient consumption behind every dish' },
      { value: 'Per rider', label: 'Delivery cash reconciled on each run' },
      { value: 'One order', label: 'Drives both the bill and the kitchen ticket' },
    ],
    quote: {
      text: 'The first month we could see food cost per dish properly, we repriced four items and stopped selling one entirely.',
      name: 'Amara N.',
      role: 'Owner',
      company: 'three-site restaurant group',
      avatar: 'portraitWoman2',
    },
    faqs: [
      { q: 'Can I run several outlets with shared suppliers?', a: 'Yes. A central store can supply each outlet through tracked transfers, so you see both the central position and each outlet’s position separately.' },
    ],
  },
  {
    slug: 'hospitality',
    group: 'hospitality',
    name: 'Hotels & accommodation',
    eyebrow: 'Hotels & accommodation',
    title: 'Rooms, folios and everything the guest consumed, on one bill',
    summary: 'Booking, occupancy, folio charges from across the property, and a checkout that posts revenue correctly by category.',
    lede: 'A guest generates a room charge, a restaurant bill, a laundry item and a minibar line over four days and expects one invoice at the end. Hospitality only works when the folio holds all of it and the revenue splits correctly afterwards.',
    heroImage: 'hotelReception',
    cardImage: 'hotelLobby',
    challenges: [
      { title: 'Charges from other outlets missing off the bill', text: 'Restaurant and bar sales can post to an open guest folio rather than being taken as separate cash sales.' },
      { title: 'Revenue blended into one line', text: 'Checkout splits revenue by category, so you can see separately what rooms, food, beverage and services each earn.' },
      { title: 'Room setup taking days', text: 'Rooms, types and rates load in bulk from a downloadable spreadsheet template.' },
      { title: 'Occupancy figures estimated', text: 'Occupancy and average rate computed from posted stays rather than counted by hand.' },
    ],
    capabilities: [
      'Room inventory, rate plans and availability',
      'Guest folios accumulating charges across the property',
      'Restaurant and bar charges posted to the room',
      'Checkout with split payment and categorised revenue posting',
      'Occupancy and average rate from posted stays',
      'Housekeeping and staff rota through Employees and Attendance',
    ],
    modules: ['accommodations', 'pos', 'sales', 'employees', 'attendance', 'reports'],
    facts: [
      { value: 'One folio', label: 'Every charge a guest makes across the property' },
      { value: 'By category', label: 'Revenue split between rooms, food and services' },
      { value: 'Template', label: 'Bulk room and rate setup from a spreadsheet' },
    ],
    quote: {
      text: 'Before, the restaurant and the rooms were two businesses that happened to share a building. Now a stay is one number.',
      name: 'Ifeoma K.',
      role: 'General Manager',
      company: 'boutique hotel',
      avatar: 'portraitWoman3',
    },
    faqs: [
      { q: 'Does it suit short-lets and serviced apartments?', a: 'Yes. Anything billed as a stay with incidental charges works identically, whatever the unit is called.' },
    ],
  },
  {
    slug: 'professional-services',
    group: 'hospitality',
    name: 'Professional services',
    eyebrow: 'Professional services',
    title: 'People, time and cost that actually reconcile',
    summary: 'Staff records, attendance, payroll and expense attribution by department, so you can see which work pays.',
    lede: 'In a services business, payroll is the cost of sales. If hours are not captured against the part of the business that used them, you have revenue and you have cost but you have no idea which engagements are profitable.',
    heroImage: 'teamMeeting',
    cardImage: 'businessPresentation',
    challenges: [
      { title: 'Time captured in a spreadsheet nobody trusts', text: 'Attendance is captured, approved and read directly by payroll, with no re-entry step in between.' },
      { title: 'Cost not attributed to the work', text: 'Payroll and expenses carry their department through to reporting.' },
      { title: 'Invoicing disconnected from delivery', text: 'Sales handles quotes, orders and invoices with receivables and ageing per client.' },
      { title: 'Month-end taking weeks', text: 'The ledger is written as the business runs, and period closings compute forward from the last snapshot.' },
    ],
    capabilities: [
      'Employee records with terms that drive the pay run',
      'Approved attendance feeding payroll directly',
      'Department-level cost attribution',
      'Client accounts with receivables and ageing',
      'Expense capture with approval thresholds',
      'P&L by department from the posted ledger',
    ],
    modules: ['employees', 'attendance', 'payroll', 'departments', 'expenses', 'reports'],
    facts: [
      { value: 'By department', label: 'Payroll and expense attribution' },
      { value: '0', label: 'Re-entry between attendance and payroll' },
      { value: 'Per client', label: 'Receivables and ageing' },
    ],
    quote: {
      text: 'We finally know which parts of the practice carry the rest. That was invisible when payroll was one line.',
      name: 'Daniel I.',
      role: 'Managing Partner',
      company: 'advisory firm',
      avatar: 'portraitMan1',
    },
    faqs: [
      { q: 'Does payroll cost me extra per employee?', a: 'No. Every plan includes unlimited users, and Payroll is priced as a module, not per head.' },
    ],
  },
  {
    slug: 'education',
    group: 'hospitality',
    name: 'Education',
    eyebrow: 'Education',
    title: 'Staff, fees and departmental budgets in one ledger',
    summary: 'Payroll for teaching and support staff, fee income tracked per payer, and spend visible by department.',
    lede: 'Schools and colleges run on payroll and fee income, two flows that usually live in completely separate places. Putting them in one ledger is what makes a departmental budget mean something.',
    heroImage: 'classroom',
    cardImage: 'universityClass',
    challenges: [
      { title: 'Fee collection tracked on paper', text: 'Payers become partner accounts with balances, ageing and statements generated from posted transactions.' },
      { title: 'Payroll disconnected from attendance', text: 'Staff attendance is approved and read directly by the pay run.' },
      { title: 'Departmental spend invisible', text: 'Expenses carry their department, so each faculty or section’s consumption is measurable.' },
      { title: 'No consolidated financial picture', text: 'Fee income, payroll cost and operating expenses all post to the same chart of accounts.' },
    ],
    capabilities: [
      'Payer accounts with balances, ageing and statements',
      'Staff records, attendance and payroll',
      'Departmental expense attribution',
      'Asset register for equipment and facilities',
      'Consolidated P&L and balance sheet',
      'Role-based access for bursary, admin and leadership',
    ],
    modules: ['employees', 'attendance', 'payroll', 'business-partners', 'expenses', 'reports'],
    facts: [
      { value: 'Per payer', label: 'Fee balances, ageing and statements' },
      { value: 'By department', label: 'Spend attribution across faculties' },
      { value: 'One ledger', label: 'Fees, payroll and operating cost together' },
    ],
    quote: {
      text: 'The bursar used to reconcile three books. Now there is one, and the governors can read it.',
      name: 'Grace M.',
      role: 'Bursar',
      company: 'independent school',
      avatar: 'portraitWoman1',
    },
    faqs: [
      { q: 'Can governors or trustees get read-only access?', a: 'Yes. Create a profile with reporting access only and no ability to change operational records.' },
    ],
  },

  /* --------------------------------------------------- industrial group -- */
  {
    slug: 'manufacturing',
    group: 'industrial',
    name: 'Manufacturing',
    eyebrow: 'Manufacturing',
    title: 'Materials in, finished goods out, and a unit cost you can defend',
    summary: 'Production and assembly that consume components and produce finished stock, with cost flowing through to the ledger.',
    lede: 'Manufacturing is the test of whether a system really understands stock. Raw material has to stop existing and finished goods have to start, at a cost that reflects what actually went in. Anything less and your margin is fiction.',
    heroImage: 'productionLine',
    cardImage: 'factoryAutomation',
    challenges: [
      { title: 'Unit cost based on assumption', text: 'Production consumes real components at real cost and produces finished goods valued accordingly.' },
      { title: 'Raw material and finished goods confused', text: 'Separate positions per item per location, with production as the recorded conversion between them.' },
      { title: 'Purchasing disconnected from production need', text: 'Reorder thresholds on components, with purchase orders, receipts and invoices matched three ways.' },
      { title: 'Labour cost outside the picture', text: 'Payroll attributed by department so production labour appears in the cost of running the plant.' },
    ],
    capabilities: [
      'Production and assembly converting components to finished goods',
      'Component reorder thresholds and purchase planning',
      'Landed cost attribution on imported materials',
      'Three-way matching on every purchase',
      'Fixed asset register with depreciation for plant and machinery',
      'Departmental payroll cost attribution',
    ],
    modules: ['inventory', 'purchase', 'assets', 'payroll', 'journals', 'reports'],
    facts: [
      { value: 'Real cost', label: 'Finished goods valued from components consumed' },
      { value: '3-way', label: 'Matching on materials purchasing' },
      { value: 'Scheduled', label: 'Depreciation on plant and machinery' },
    ],
    quote: {
      text: 'We were pricing on a cost we had worked out two years earlier. The real number was eighteen per cent higher.',
      name: 'Emeka U.',
      role: 'Production Director',
      company: 'food processing plant',
      avatar: 'portraitMan3',
    },
    faqs: [
      { q: 'Does it handle multi-level assemblies?', a: 'Production converts components into finished items, and a finished item can itself be a component of another build, so multi-level structures are supported.' },
    ],
  },
  {
    slug: 'construction',
    group: 'industrial',
    name: 'Construction',
    eyebrow: 'Construction',
    title: 'Site cost, labour and plant, attributed where they were spent',
    summary: 'Expense and payroll attribution by site, materials purchasing with receipt matching, and an asset register for plant.',
    lede: 'Construction loses money on sites rather than in the office, and usually finds out months later. Attributing labour, materials and plant to the job as they are consumed is the difference between managing a project and auditing it.',
    heroImage: 'constructionCrew',
    cardImage: 'constructionSite',
    challenges: [
      { title: 'Site cost known only at the end', text: 'Expenses and payroll carry their department, so a site can be set up as a cost centre and tracked as it runs.' },
      { title: 'Materials bought and never accounted for', text: 'Purchase orders, goods receipt against the order, and invoice matching on every delivery.' },
      { title: 'Plant treated as an expense', text: 'Fixed asset register with depreciation, location and custody, so plant stays on the balance sheet where it belongs.' },
      { title: 'Casual labour outside the system', text: 'Attendance capture and payroll handle variable crews with approval before hours become payable.' },
    ],
    capabilities: [
      'Site-level cost attribution through departments',
      'Materials purchasing with goods receipt and invoice matching',
      'Plant and equipment asset register with custody tracking',
      'Attendance and payroll for variable site crews',
      'Expense capture with approval thresholds',
      'P&L by site from the posted ledger',
    ],
    modules: ['expenses', 'purchase', 'assets', 'attendance', 'payroll', 'reports'],
    facts: [
      { value: 'Per site', label: 'Labour, materials and plant cost attribution' },
      { value: 'Tracked', label: 'Plant location and custody on the register' },
      { value: 'Approved', label: 'Crew hours signed off before they are payable' },
    ],
    quote: {
      text: 'Knowing site cost in week six instead of month four is the whole difference. We have walked away from two jobs because of it.',
      name: 'Bola F.',
      role: 'Contracts Manager',
      company: 'civil contractor',
      avatar: 'portraitMan2',
    },
    faqs: [
      { q: 'Can each site be its own cost centre?', a: 'Yes. Departments are used as cost centres, so expenses and payroll attributed to a site flow through to per-site reporting.' },
    ],
  },
  {
    slug: 'logistics',
    group: 'industrial',
    name: 'Logistics & transport',
    eyebrow: 'Logistics & transport',
    title: 'Dispatch, fleet and proof of delivery, reconciled every day',
    summary: 'Delivery runs with assigned riders and vehicles, proof of handover, cash reconciliation and a fleet asset register.',
    lede: 'Goods and cash moving around without supervision is the oldest leak in the business. Every run becomes a record: what went out, who took it, what came back, and what is still unaccounted for at the end of the day.',
    heroImage: 'logisticsTruck',
    cardImage: 'deliveryRider',
    challenges: [
      { title: 'Cash collected on the road and partially returned', text: 'Per-rider, per-run reconciliation comparing what should have been collected against what was handed in.' },
      { title: 'No record of handover', text: 'Proof of delivery captured at the point of handover, so disputes are settled with a record.' },
      { title: 'Stock missing while in transit', text: 'Goods out for delivery visible as in-transit rather than absent from the warehouse position.' },
      { title: 'Vehicles treated as expenses', text: 'Fleet on the asset register with depreciation, maintenance history and custody.' },
    ],
    capabilities: [
      'Dispatch raised directly from the sales order',
      'Rider and vehicle assignment with live visibility of what is out',
      'Proof of delivery captured at handover',
      'Cash-on-delivery reconciliation per rider and per run',
      'Failed and partial deliveries handled properly',
      'Fleet asset register with maintenance history',
    ],
    modules: ['delivery', 'sales', 'inventory', 'assets', 'business-partners', 'reports'],
    facts: [
      { value: 'Per run', label: 'Cash reconciliation by named rider' },
      { value: 'In transit', label: 'Stock visibility while goods are out' },
      { value: 'On the register', label: 'Fleet with depreciation and maintenance' },
    ],
    quote: {
      text: 'The reconciliation screen paid for the system in the first quarter. We were not being robbed, we were just never checking.',
      name: 'Kelechi D.',
      role: 'Fleet Manager',
      company: 'last-mile logistics operator',
      avatar: 'portraitMan4',
    },
    faqs: [
      { q: 'Can riders work offline between stops?', a: 'Yes. Delivery and reconciliation screens are built for phones and continue working without a connection, syncing when coverage returns.' },
    ],
  },
  {
    slug: 'agriculture',
    group: 'industrial',
    name: 'Agriculture & agribusiness',
    eyebrow: 'Agriculture',
    title: 'Inputs, harvest, storage and sale, on one set of books',
    summary: 'Input purchasing, produce as stock, seasonal labour payroll and equipment on the asset register.',
    lede: 'Agribusiness is manufacturing with weather. Inputs are bought, a crop is produced, it is stored and then sold. The cost of producing it is spread across months of labour, fuel and material that usually never get attributed to anything.',
    heroImage: 'farmer',
    cardImage: 'harvest',
    challenges: [
      { title: 'Cost of production never calculated', text: 'Inputs purchased as stock, consumed through production, with labour attributed by department.' },
      { title: 'Harvest held without a value', text: 'Produce held as stock with a position per store and a value that flows to the balance sheet.' },
      { title: 'Seasonal labour outside payroll', text: 'Attendance capture and payroll handle variable crews with approval before hours become payable.' },
      { title: 'Equipment expensed rather than capitalised', text: 'Tractors, irrigation and processing equipment on the asset register with depreciation.' },
    ],
    capabilities: [
      'Input purchasing with goods receipt and invoice matching',
      'Produce held as stock with per-store positions',
      'Production converting inputs and labour into output',
      'Seasonal and casual crew attendance and payroll',
      'Equipment asset register with maintenance history',
      'Cost of production visible per cycle',
    ],
    modules: ['inventory', 'purchase', 'payroll', 'assets', 'expenses', 'reports'],
    facts: [
      { value: 'Per cycle', label: 'Cost of production from real inputs' },
      { value: 'Per store', label: 'Harvest held with a real stock value' },
      { value: 'Capitalised', label: 'Equipment on the register, not in the P&L' },
    ],
    quote: {
      text: 'We knew what we sold for. We had never once known what it cost us to grow.',
      name: 'Hassan Y.',
      role: 'Farm Director',
      company: 'mixed agribusiness',
      avatar: 'portraitMan3',
    },
    faqs: [
      { q: 'Does it handle seasonal workforce changes?', a: 'Yes. Employees can be onboarded and offboarded as crews change, with attendance approved per period and payroll reading only approved hours.' },
    ],
  },

  /* --------------------------------------------------------- care group -- */
  {
    slug: 'healthcare',
    group: 'care',
    name: 'Healthcare',
    eyebrow: 'Healthcare',
    title: 'Rotas, consumables and billing that do not fight each other',
    summary: 'Staff scheduling and payroll, consumable stock control with expiry visibility, and patient billing with receivables.',
    lede: 'Clinics and hospitals run three systems that rarely talk: the rota, the store and the till. When consumable stock, staff hours and billing all post to one ledger, the cost of delivering care becomes measurable.',
    heroImage: 'medicalTeam',
    cardImage: 'hospitalStaff',
    challenges: [
      { title: 'Consumables running out mid-shift', text: 'Stock positions per store with reorder thresholds surfaced before the shelf empties.' },
      { title: 'Rota and payroll maintained separately', text: 'Attendance approved by supervisors and read directly by the pay run.' },
      { title: 'Billing and collection untracked', text: 'Payer accounts with balances, ageing and statements built from posted transactions.' },
      { title: 'Departmental cost invisible', text: 'Payroll and expenses carry their department, so each unit’s running cost is measurable.' },
    ],
    capabilities: [
      'Consumable stock control per store with reorder signals',
      'Staff records, shift patterns, attendance and payroll',
      'Payer accounts with ageing and statements',
      'Departmental cost attribution across units',
      'Equipment asset register with maintenance history',
      'Role-based access appropriate to clinical and administrative staff',
    ],
    modules: ['employees', 'attendance', 'payroll', 'inventory', 'business-partners', 'reports'],
    facts: [
      { value: 'Per store', label: 'Consumable stock positions and reorder signals' },
      { value: 'By unit', label: 'Cost attribution across departments' },
      { value: 'Approved', label: 'Hours signed off before they are payable' },
    ],
    quote: {
      text: 'Running out of consumables mid-shift was normal. It is not any more, and nobody had to start a spreadsheet.',
      name: 'Dr. Ngozi A.',
      role: 'Clinical Director',
      company: 'multi-site clinic group',
      avatar: 'portraitWoman2',
    },
    faqs: [
      { q: 'Is this a clinical records system?', a: 'No. Enterprise Compute handles the business side of running a healthcare operation: staff, stock, billing and accounts. It does not hold clinical records, and is designed to sit alongside whatever clinical system you use.' },
    ],
  },
  {
    slug: 'nonprofit',
    group: 'care',
    name: 'Non-profit & NGO',
    eyebrow: 'Non-profit',
    title: 'Restricted funds, grant spend and reporting donors will accept',
    summary: 'Departmental fund attribution, approval thresholds on spend, and statements produced from posted transactions.',
    lede: 'Non-profits are audited on whether money went where it was supposed to. That is an attribution problem, and attribution has to happen as the spend occurs rather than be reconstructed later for the report.',
    heroImage: 'teamCollaboration',
    cardImage: 'teamWhiteboard',
    challenges: [
      { title: 'Restricted funds spent untracked', text: 'Departments used as fund codes, so every expense and payroll cost carries the fund it was charged to.' },
      { title: 'Approval discipline missing', text: 'Spend thresholds route to the right approver, with the decision and the approver recorded.' },
      { title: 'Donor reporting rebuilt by hand', text: 'Statements and departmental P&L produced directly from posted transactions.' },
      { title: 'Assets bought with grant money untracked', text: 'Asset register with location, custody and depreciation.' },
    ],
    capabilities: [
      'Fund attribution through departments',
      'Approval thresholds with recorded decisions',
      'Full audit trail on every posted record',
      'Payroll with departmental cost attribution',
      'Asset register with custody tracking',
      'Departmental and consolidated reporting',
    ],
    modules: ['expenses', 'journals', 'reports', 'employees', 'payroll', 'assets'],
    facts: [
      { value: 'Per fund', label: 'Attribution on every expense and pay cost' },
      { value: 'Recorded', label: 'Approver and decision on threshold spend' },
      { value: 'From source', label: 'Donor reporting built from posted transactions' },
    ],
    quote: {
      text: 'The audit used to take three weeks of preparation. Most of that work was just proving where money went, and now that is a report.',
      name: 'Ruth O.',
      role: 'Finance Manager',
      company: 'international NGO',
      avatar: 'portraitWoman3',
    },
    faqs: [
      { q: 'Can we separate restricted and unrestricted funds?', a: 'Yes. Departments act as fund codes, so costs carry their fund through to reporting and a restricted fund’s spend can be reported on independently.' },
    ],
  },
]

export const INDUSTRY_BY_SLUG = INDUSTRIES.reduce((acc, industry) => {
  acc[industry.slug] = industry
  return acc
}, {})

export const industriesInGroup = (key) => INDUSTRIES.filter((i) => i.group === key)

export default INDUSTRIES
