/* ============================================================================
   Product catalogue content for /products and /products/:slug.
   ----------------------------------------------------------------------------
   `slug` matches the real module key in
   wageserver/UserModule/Billing/moduleCatalog.js wherever one exists, so the
   marketing page for a module and the thing a tenant actually buys cannot
   drift apart. Two entries (offline-sync, positions) describe platform
   behaviour rather than separately billed modules and are flagged with
   `billable: false`.

   `tier` likewise mirrors the catalogue: 'free' modules are included on every
   workspace forever, 'standard' ones are priced per module. The live price is
   never hardcoded here — the pricing page reads it from /platform-modules.
   ========================================================================= */

export const PRODUCT_CATEGORIES = [
  {
    key: 'finance',
    name: 'Finance & accounting',
    blurb: 'A real double-entry ledger that is written to by the business as it runs, not reconstructed afterwards.',
    image: 'accountantDesk',
  },
  {
    key: 'commerce',
    name: 'Operations & commerce',
    blurb: 'Selling, buying, stock and fulfilment. These are the modules that move goods and money every day.',
    image: 'warehouseLogistics',
  },
  {
    key: 'people',
    name: 'People & partners',
    blurb: 'Who works for you, when they worked, what they are owed, and who you trade with.',
    image: 'teamMeeting',
  },
  {
    key: 'platform',
    name: 'Platform & intelligence',
    blurb: 'The assistant, the dashboard, the permissions model and the offline engine underneath everything else.',
    image: 'dataCentre',
  },
]

export const PRODUCTS = [
  /* ------------------------------------------------------------ platform -- */
  {
    slug: 'dashboard',
    name: 'Dashboard',
    category: 'platform',
    tier: 'free',
    billable: true,
    eyebrow: 'Dashboard',
    title: 'The one screen that answers "how are we doing" honestly',
    summary: 'A live operating picture built from posted records: revenue, orders, stock movement, staff on duty and cash position, as of right now.',
    lede: 'Most dashboards are a slide. This one is a read of the ledger. Every figure on it traces back to a posted transaction you can open, and it updates the moment that transaction is written rather than overnight.',
    heroImage: 'realtimeDashboard',
    cardImage: 'dashboardScreen',
    capabilities: [
      { title: 'Live figures, not a nightly snapshot', text: 'Tenant-scoped server-sent events push changes to every open dashboard as transactions post, so two managers looking at the same number are looking at the same number.' },
      { title: 'Drill from summary to source', text: 'Every tile is a query, not a stored total. Click revenue and you get the sales behind it; click stock value and you get the items and the movements.' },
      { title: 'Closing-aware totals', text: 'Period figures are computed from the last closing snapshot forward instead of recomputing from day one, so the dashboard stays fast as history grows.' },
      { title: 'Scoped to what you are allowed to see', text: 'A warehouse supervisor and a finance lead open the same page and get different tiles, driven by the same role permissions that govern the rest of the platform.' },
      { title: 'Multi-site roll-up', text: 'Group totals across locations, or filter to a single branch, without maintaining a separate consolidated report.' },
      { title: 'Exceptions surfaced, not buried', text: 'Negative stock, unposted sessions, overdue approvals and failing syncs appear as actionable items rather than something you discover at month-end.' },
    ],
    outcomes: [
      { value: 'Real time', label: 'Figures refresh as transactions post, not on a schedule' },
      { value: '1', label: 'Source of record behind every tile on the page' },
      { value: '0', label: 'Spreadsheets needed to produce the daily number' },
    ],
    howItWorks: [
      { step: 'Transactions post', text: 'A sale, goods receipt, pay run or expense is written through its module and journaled.' },
      { step: 'Summaries update', text: 'The affected period summaries are updated incrementally from the last closing snapshot.' },
      { step: 'Screens refresh', text: 'Every connected session for that tenant receives the change and re-renders the affected tiles.' },
    ],
    worksWith: ['sales', 'inventory', 'journals', 'reports'],
    faqs: [
      { q: 'Is the dashboard included on every plan?', a: 'Yes. Dashboard is one of the free core modules available on every workspace, on every plan, permanently.' },
      { q: 'How current are the figures?', a: 'They reflect posted transactions as of the moment you look. There is no nightly batch. Updates get pushed to open sessions as records are written.' },
      { q: 'Can different staff see different tiles?', a: 'Yes. Visibility follows the same role-based permissions as the rest of the platform, so the dashboard never becomes a back door to figures someone is not cleared for.' },
    ],
  },
  {
    slug: 'epsilon',
    name: 'Epsilon AI assistant',
    category: 'platform',
    tier: 'standard',
    billable: true,
    perSeat: true,
    eyebrow: 'AI assistant · paid add-on',
    title: 'An assistant that actually knows the business it is talking about',
    summary: 'Epsilon is wired into your live records. It explains why a number is what it is, why a transaction is blocked, and who can approve it.',
    lede: 'A general chatbot can tell you what a trial balance is. Epsilon can tell you why yours does not balance, which journal caused it, and who posted it. It reads your actual records, not a summary of them and not a training set.',
    heroImage: 'dataAnalytics',
    cardImage: 'analyticsScreen',
    capabilities: [
      { title: 'Traces a number to its cause', text: 'Ask why stock on an item is lower than expected and Epsilon walks the real movement history of sales, transfers, adjustments and production, instead of guessing.' },
      { title: 'Explains blockers, names approvers', text: 'When something will not post, it says which rule stopped it and which specific person holds the permission to clear it, instead of "contact your administrator".' },
      { title: 'Reads across every module', text: 'Questions that span payroll, inventory and the ledger get one answer, because it queries the same records those modules write to.' },
      { title: 'Generates reporting on demand', text: 'Ask for a margin breakdown by location for last quarter and it builds it from posted figures, with the query it used shown alongside.' },
      { title: 'Proposes, never acts alone', text: 'It can draft a purchase order or a correcting entry, but nothing is written until a human with the right permission confirms it.' },
      { title: 'Respects the permission model', text: 'Epsilon can only see what the person asking can see. It is not a privileged back channel into restricted figures.' },
      { title: 'Voice in, plain language out', text: 'Staff on the floor can ask out loud and get an answer in the same sentence they would use with a colleague.' },
      { title: 'Per-seat, bought when you need it', text: 'Licensed per seat from inside your workspace, with a separate usage balance, so it never inflates the base platform cost for teams that do not want it.' },
    ],
    outcomes: [
      { value: 'Every', label: 'Module readable in a single question' },
      { value: '0', label: 'Changes written without explicit human confirmation' },
      { value: 'Per seat', label: 'Licensing, so only the people who use it are billed' },
    ],
    howItWorks: [
      { step: 'Ask in plain language', text: 'By text or voice, from anywhere in the workspace.' },
      { step: 'Epsilon queries your records', text: 'Scoped to your tenant and to your own permission set.' },
      { step: 'You get the answer and the trail', text: 'With the underlying transactions cited, so the answer is checkable.' },
      { step: 'You confirm any change', text: 'Proposed edits stay proposals until someone authorised accepts them.' },
    ],
    worksWith: ['dashboard', 'journals', 'inventory', 'payroll'],
    faqs: [
      { q: 'Is Epsilon included in the free trial?', a: 'No. Epsilon is the one capability that sits outside both the trial and the module calculator, because it is priced per seat plus usage rather than as a flat monthly module. You add seats from Settings → Billing once your workspace exists.' },
      { q: 'Can Epsilon change my data?', a: 'Only with confirmation. It can draft a purchase order or propose a correction, but the write only happens once a person with the relevant permission accepts it. Never on its own.' },
      { q: 'Can it see things I am not allowed to see?', a: 'No. Epsilon answers within the asking user’s own permission scope, so it cannot be used to read figures that person could not open directly.' },
      { q: 'What does it cost?', a: 'A per-seat monthly price plus a per-1,000-token usage balance. Both are shown live on the pricing page and inside your workspace billing settings.' },
    ],
  },
  {
    slug: 'settings',
    name: 'Settings & governance',
    category: 'platform',
    tier: 'free',
    billable: true,
    eyebrow: 'Settings & governance',
    title: 'Who can see it, who can change it, who has to approve it',
    summary: 'Role-based access, approval routing, account mapping and workspace configuration, all in one place.',
    lede: 'Control is not a feature you bolt on after a mistake. Every module reads the same permission model, so granting someone the ability to post a journal, or removing their ability to discount a sale, is one decision in one place.',
    heroImage: 'cyberSecurity',
    cardImage: 'dataProtection',
    capabilities: [
      { title: 'Granular, per-action permissions', text: 'Not just "can open Inventory" but can they adjust stock, approve a transfer, or only look. Set per profile and applied everywhere.' },
      { title: 'Approval workflows', text: 'Route a discount, a write-off, a purchase above a threshold or a payroll run to the person who should sign it, with a record of who did.' },
      { title: 'Account mapping', text: 'Decide once which ledger accounts operational activity posts to, so sales, cost of sales, stock and expenses land where your accountant expects.' },
      { title: 'Full audit trail', text: 'Who changed what, when, and from where. Kept for every posted record, not just for logins.' },
      { title: 'Workspace and branch configuration', text: 'Locations, warehouses, currencies, tax treatment, document numbering and receipt layouts.' },
      { title: 'Module entitlement control', text: 'Turn modules on as you need them. Dependencies are added automatically and the new price applies from your next renewal, not the day you switch it on.' },
    ],
    outcomes: [
      { value: 'Per action', label: 'Permission granularity, not per screen' },
      { value: 'Every', label: 'Posted record carries an audit trail' },
      { value: '1', label: 'Place to change access for the whole platform' },
    ],
    howItWorks: [
      { step: 'Define profiles', text: 'Build the roles your business actually has: cashier, supervisor, storekeeper, accountant, owner.' },
      { step: 'Assign actions', text: 'Grant view, create, edit, approve, post and export independently per module.' },
      { step: 'Route approvals', text: 'Attach thresholds and approvers to the actions that need a second pair of eyes.' },
    ],
    worksWith: ['employees', 'journals', 'dashboard', 'offline-sync'],
    faqs: [
      { q: 'Does adding a module cost me immediately?', a: 'No. You can enable a module straight away and the higher price applies from your next renewal date, not pro-rata on the day.' },
      { q: 'Can I stop a cashier from discounting?', a: 'Yes. Discounting is a separate permission from selling, so a till operator can process sales without the ability to change a price.' },
    ],
  },
  {
    slug: 'offline-sync',
    name: 'Offline & sync',
    category: 'platform',
    tier: 'free',
    billable: false,
    eyebrow: 'Offline & sync',
    title: 'Keep trading when the network does not',
    summary: 'Local-first operation with an IndexedDB queue, so sales, counts and entries continue during an outage and reconcile cleanly afterwards.',
    lede: 'A connectivity drop should cost you a few minutes of reporting latency, not a day of revenue. Work continues locally and reconciles on reconnect, with conflicts surfaced rather than silently overwritten.',
    heroImage: 'posTerminal',
    cardImage: 'shopkeeper',
    capabilities: [
      { title: 'Sell through an outage', text: 'The POS keeps taking orders, printing receipts and deducting stock against its local copy while the connection is gone.' },
      { title: 'Durable local queue', text: 'Pending changes are written to IndexedDB on the device, so a browser refresh or a flat battery does not lose the queue.' },
      { title: 'Ordered, idempotent replay', text: 'Each queued change carries a client transaction id, so a retry after a half-failed upload cannot post the same sale twice.' },
      { title: 'Conflicts surfaced, not swallowed', text: 'If the same record changed on both sides, the clash is raised for a human to settle instead of being resolved by whichever write landed last.' },
      { title: 'Summaries catch up automatically', text: 'Once a batch lands, the affected period summaries and dashboards recompute, so the figures converge without manual intervention.' },
      { title: 'Visible sync state', text: 'Staff can always see whether they are online, how many changes are pending and when the last successful sync happened.' },
    ],
    outcomes: [
      { value: '0', label: 'Sales lost to a connectivity drop' },
      { value: 'Device', label: 'Local durability, so the queue survives a refresh' },
      { value: 'Auto', label: 'Reconciliation and summary refresh on reconnect' },
    ],
    howItWorks: [
      { step: 'Connection drops', text: 'The client detects it and switches to local-first operation.' },
      { step: 'Work continues', text: 'Transactions are written locally with client transaction ids and queued.' },
      { step: 'Connection returns', text: 'The queue replays in order; duplicates are rejected by id.' },
      { step: 'Figures reconcile', text: 'Summaries and dashboards recompute and every session refreshes.' },
    ],
    worksWith: ['pos', 'inventory', 'sales', 'dashboard'],
    faqs: [
      { q: 'What happens if two tills sell the last unit while offline?', a: 'Both sales post and the resulting negative position is raised as an exception for someone to resolve, rather than one sale being discarded without anybody being told.' },
      { q: 'Is there a desktop option for poor connectivity?', a: 'Yes. Enterprise Compute also ships as a desktop application with a bundled local database for sites where the network is unreliable rather than occasionally down.' },
    ],
  },

  /* ------------------------------------------------------------- commerce -- */
  {
    slug: 'pos',
    name: 'Point of Sale',
    category: 'commerce',
    tier: 'standard',
    billable: true,
    eyebrow: 'Point of Sale',
    title: 'Where the money actually changes hands',
    summary: 'A fast, offline-capable till for shops, restaurants and forecourts, with sessions, multiple payment types and real-time stock deduction.',
    lede: 'The till is the one screen your team uses hundreds of times a day, so it has to be quick, forgiving and honest about cash. Every sale deducts stock, posts revenue and lands in the session the operator is accountable for.',
    heroImage: 'posTerminal',
    cardImage: 'posCheckout',
    capabilities: [
      { title: 'Session-based cash accountability', text: 'Open with a declared float, sell, close with a count. Variance is calculated and attributed to the operator, not absorbed into a general shortfall.' },
      { title: 'Real-time stock deduction', text: 'A sale moves inventory the moment it is completed, so the shelf, the system and the dashboard agree.' },
      { title: 'Runs offline', text: 'Keeps selling without a network and reconciles automatically when the connection returns.' },
      { title: 'Multiple payment methods', text: 'Cash, card, transfer and split payments on a single order, each recorded separately for reconciliation.' },
      { title: 'Tables and order types', text: 'Dine-in table management, takeaway and delivery orders handled in the same flow, with kitchen and customer receipt variants.' },
      { title: 'Parallel sessions and locations', text: 'Run several tills across several sites at once, each with its own stock source and its own cash position.' },
      { title: 'Returns, voids and discounts under permission', text: 'Each is a distinct permission, so you decide who can do what without taking them off the till.' },
      { title: 'Receipts that suit the job', text: 'Customer, kitchen and operational receipt layouts, printed or digital.' },
    ],
    outcomes: [
      { value: 'Seconds', label: 'From item scan to completed, posted sale' },
      { value: 'Offline', label: 'Selling continues through a network outage' },
      { value: 'Per session', label: 'Cash variance attributed, not absorbed' },
    ],
    howItWorks: [
      { step: 'Open a session', text: 'Operator declares the opening float against a specific till and warehouse.' },
      { step: 'Sell', text: 'Orders are taken, paid and receipted; stock and revenue post as each completes.' },
      { step: 'Close and count', text: 'Declared cash is compared against expected, and the variance is recorded.' },
      { step: 'It lands in the ledger', text: 'Revenue, cost of sales and cash all post to the mapped accounts automatically.' },
    ],
    worksWith: ['inventory', 'sales', 'delivery', 'journals'],
    faqs: [
      { q: 'Can I use it on a tablet?', a: 'Yes. The POS is built for touch and runs in a browser on tablets and desktops, as well as inside the desktop application.' },
      { q: 'What stops a cashier changing prices?', a: 'Discounting and price override are separate permissions from processing a sale, so a cashier can sell all day without the ability to alter a price.' },
      { q: 'Does POS require Inventory and Sales?', a: 'Yes. POS depends on both, so enabling it adds them automatically and stock movement and revenue posting work the way you would expect.' },
    ],
  },
  {
    slug: 'inventory',
    name: 'Inventory',
    category: 'commerce',
    tier: 'standard',
    billable: true,
    eyebrow: 'Inventory',
    title: 'Knowing exactly what you have, right now',
    summary: 'Multi-warehouse stock control with transfers, adjustments, counts, production and item-level movement history.',
    lede: 'Stock is the number most businesses are least sure of and most exposed to. Here it is a running position built from recorded movements, so when the figure is wrong you can see the movement that made it wrong.',
    heroImage: 'inventoryCount',
    cardImage: 'warehouseRacks',
    capabilities: [
      { title: 'Position per item, per location', text: 'Not one company-wide number. Know what is in which warehouse, shop floor or kitchen store at any moment.' },
      { title: 'Every movement recorded', text: 'Sales, purchases, transfers, adjustments, production consumption and wastage each leave a dated, attributed record you can open.' },
      { title: 'Transfers between locations', text: 'Raise, dispatch and receive transfers, with in-transit stock visible and discrepancies on receipt raised rather than absorbed.' },
      { title: 'Counts and reconciliation', text: 'Run a full or partial count, enter what you actually found, and post the variance as a recorded adjustment with a reason.' },
      { title: 'Production and assembly', text: 'Consume components and produce finished goods, so a kitchen or workshop’s output is reflected in both stock and cost.' },
      { title: 'Low-stock signals', text: 'Reorder thresholds per item per location, surfaced on the dashboard before the shelf is empty.' },
      { title: 'Costing that feeds the ledger', text: 'Stock value and cost of sales post to the accounts automatically, so the balance sheet reflects what is actually on the shelf.' },
      { title: 'Spreadsheet import for setup', text: 'Load an opening catalogue and opening quantities from a template rather than typing a thousand items.' },
    ],
    outcomes: [
      { value: 'Per location', label: 'Stock positions, not one blended number' },
      { value: 'Every', label: 'Movement attributed to a person and a document' },
      { value: 'Auto', label: 'Stock value and cost of sales posted to the ledger' },
    ],
    howItWorks: [
      { step: 'Load the catalogue', text: 'Items, units, costs and opening quantities per location.' },
      { step: 'Trade normally', text: 'Sales, purchases, transfers and production move stock as they happen.' },
      { step: 'Count periodically', text: 'Record what is physically there; variances post as explained adjustments.' },
    ],
    worksWith: ['pos', 'purchase', 'sales', 'journals'],
    faqs: [
      { q: 'Can I run several warehouses?', a: 'Yes. Locations are first-class: every item holds a position per location, and transfers between them are tracked end to end.' },
      { q: 'What happens if stock goes negative?', a: 'It is allowed to happen rather than blocking a live sale, but the negative position is raised as an exception so it gets investigated instead of hiding in the data.' },
    ],
  },
  {
    slug: 'sales',
    name: 'Sales',
    category: 'commerce',
    tier: 'standard',
    billable: true,
    eyebrow: 'Sales',
    title: 'Every order, invoice and naira of revenue, in one place',
    summary: 'Quotes, orders, invoices, credit notes and receipts, with revenue and receivables posting straight into the ledger.',
    lede: 'Sales is where the business makes its money and where most reporting disputes start. One record per order, one revenue posting, one receivable. What the sales report says and what the ledger says cannot disagree.',
    heroImage: 'businessGrowth',
    cardImage: 'posCard',
    capabilities: [
      { title: 'Quote to cash in one chain', text: 'A quote becomes an order becomes an invoice becomes a receipt, with each step linked, so nothing is rekeyed and nothing is lost between stages.' },
      { title: 'Credit sales and receivables', text: 'Track who owes what and how long it has been outstanding, by customer, with the ledger kept in step.' },
      { title: 'Stock reserved and released', text: 'Confirmed orders hold stock so you do not sell the same unit twice, and release it if the order is cancelled.' },
      { title: 'Pricing and discount control', text: 'Price lists, customer-specific pricing and discount limits enforced by permission rather than by trust.' },
      { title: 'Credit notes and returns', text: 'Reverse a sale properly: stock back in, revenue reversed, receivable adjusted, and all of it traceable to the original document.' },
      { title: 'Revenue recognised automatically', text: 'Revenue, cost of sales, tax and receivables post to the accounts you mapped in Settings, with no month-end journal exercise.' },
    ],
    outcomes: [
      { value: '1', label: 'Chain from quote through to cash received' },
      { value: 'Auto', label: 'Revenue, tax and receivable postings' },
      { value: 'Per customer', label: 'Outstanding balance and ageing' },
    ],
    howItWorks: [
      { step: 'Raise the order', text: 'From the POS, from a quote, or directly for a credit customer.' },
      { step: 'Fulfil it', text: 'Stock moves, and delivery is dispatched where relevant.' },
      { step: 'Invoice and collect', text: 'The receivable is tracked until payment is recorded against it.' },
    ],
    worksWith: ['pos', 'inventory', 'delivery', 'business-partners'],
    faqs: [
      { q: 'Does Sales require Inventory?', a: 'Yes. Sales depends on Inventory so that every order can move real stock and post a real cost of sale. Enabling Sales adds Inventory automatically.' },
      { q: 'Can I invoice without the POS?', a: 'Yes. The POS is for over-the-counter trade; Sales handles quotes, credit orders and invoicing independently of it.' },
    ],
  },
  {
    slug: 'purchase',
    name: 'Purchase',
    category: 'commerce',
    tier: 'standard',
    billable: true,
    eyebrow: 'Purchase',
    title: 'One real record behind every purchase',
    summary: 'Purchase orders, goods receipt, supplier invoices and payables, with stock and cost updated on receipt.',
    lede: 'Buying badly is quieter than selling badly but just as expensive. Every order placed, every delivery received and every invoice matched leaves a record, so what you were charged and what actually arrived can be compared.',
    heroImage: 'warehouseTeam',
    cardImage: 'logisticsTruck',
    capabilities: [
      { title: 'Purchase orders with approval', text: 'Raise an order, route it for approval above a threshold, and send it with a document the supplier can work from.' },
      { title: 'Goods receipt against the order', text: 'Receive what actually arrived, including partial deliveries, with short and over deliveries recorded rather than quietly accepted.' },
      { title: 'Three-way matching', text: 'Order, receipt and supplier invoice compared, so you are not paying for forty cartons when thirty-eight were delivered.' },
      { title: 'Landed cost', text: 'Attribute freight, duty and handling to the goods they relate to, so item cost, and therefore margin, reflects reality.' },
      { title: 'Payables and supplier balances', text: 'What you owe, to whom, and when it is due, kept in step with the ledger.' },
      { title: 'Stock and cost updated on receipt', text: 'Receiving goods raises the stock position and the inventory value at the same moment, with the matching ledger entries.' },
    ],
    outcomes: [
      { value: '3-way', label: 'Match across order, receipt and invoice' },
      { value: 'On receipt', label: 'Stock and inventory value updated together' },
      { value: 'Per supplier', label: 'Payables balance and ageing' },
    ],
    howItWorks: [
      { step: 'Raise and approve', text: 'A purchase order is created and routed to whoever needs to sign it.' },
      { step: 'Receive the goods', text: 'What physically arrived is recorded against the order.' },
      { step: 'Match and pay', text: 'The supplier invoice is matched to the receipt and the payable is settled.' },
    ],
    worksWith: ['inventory', 'business-partners', 'expenses', 'journals'],
    faqs: [
      { q: 'Does Purchase require Inventory?', a: 'Yes, because receiving goods has to update a real stock position and a real inventory value. Enabling Purchase adds Inventory automatically.' },
      { q: 'Can I record a purchase that is not stock?', a: 'Services and consumables that are not held as stock belong in Expenses, which posts straight to the relevant cost account.' },
    ],
  },
  {
    slug: 'delivery',
    name: 'Delivery',
    category: 'commerce',
    tier: 'standard',
    billable: true,
    eyebrow: 'Delivery',
    title: 'Dispatch, track and reconcile every order that leaves the building',
    summary: 'Turn orders into dispatches, assign riders and vehicles, confirm delivery, and reconcile cash collected on the road.',
    lede: 'Goods leaving your premises with cash coming back is the part of the day with the least supervision and the most leakage. Delivery makes each trip a record: what went out, who took it, what came back.',
    heroImage: 'deliveryDriver',
    cardImage: 'deliveryVan',
    capabilities: [
      { title: 'Dispatch straight from the order', text: 'An order becomes a delivery without rekeying, carrying the items, the address and the amount due.' },
      { title: 'Rider and vehicle assignment', text: 'Know who has which consignment, and see what is still out at any point in the day.' },
      { title: 'Proof of delivery', text: 'Confirmation captured at the point of handover, so disputes are settled with a record instead of a recollection.' },
      { title: 'Cash-on-delivery reconciliation', text: 'Compare what should have been collected against what was handed in, per rider, per run. The dedicated reconciliation review screen exists for exactly this.' },
      { title: 'Failed and partial deliveries', text: 'Record a refusal or a part-delivery properly, returning the right stock and adjusting the right receivable.' },
      { title: 'Stock stays accurate in transit', text: 'Goods out for delivery are visible as in-transit rather than silently missing from the warehouse position.' },
    ],
    outcomes: [
      { value: 'Per run', label: 'Cash reconciliation by rider' },
      { value: 'In transit', label: 'Stock visibility while goods are out' },
      { value: 'Recorded', label: 'Proof of delivery at handover' },
    ],
    howItWorks: [
      { step: 'Order confirmed', text: 'A delivery is raised from the sales order.' },
      { step: 'Assigned and dispatched', text: 'Rider and vehicle attached; stock moves to in-transit.' },
      { step: 'Delivered and reconciled', text: 'Handover confirmed, cash reconciled, receivable cleared.' },
    ],
    worksWith: ['sales', 'pos', 'inventory', 'business-partners'],
    faqs: [
      { q: 'Does Delivery require Sales?', a: 'Yes. A delivery exists to fulfil an order, so Sales is added automatically when Delivery is enabled.' },
      { q: 'Can riders use it on a phone?', a: 'Yes. The delivery and reconciliation screens are built for a phone, including while offline between stops.' },
    ],
  },
  {
    slug: 'accommodations',
    name: 'Accommodations',
    category: 'commerce',
    tier: 'standard',
    billable: true,
    eyebrow: 'Accommodations',
    title: 'Room and stay billing, done properly',
    summary: 'Rooms, rates, bookings, folio charges and checkout billing for hotels, guest houses and serviced accommodation.',
    lede: 'A stay is not a single sale. It is a room charge plus everything the guest consumed, accumulated over several days and settled once. Accommodations keeps that folio straight and posts it correctly at checkout.',
    heroImage: 'hotelReception',
    cardImage: 'hotelRoom',
    capabilities: [
      { title: 'Rooms, types and rates', text: 'Configure your inventory of rooms with rate plans, and load the whole thing from a spreadsheet template rather than typing each one.' },
      { title: 'Bookings and availability', text: 'See what is free, what is occupied and what is due to check out, without a separate diary.' },
      { title: 'Guest folios', text: 'Room nights, restaurant charges, minibar and service items accumulate against the stay and settle as one bill.' },
      { title: 'Charges from other modules', text: 'A meal rung up on the restaurant till can post to the guest folio rather than being taken as a separate cash sale.' },
      { title: 'Checkout and settlement', text: 'Produce the final bill, take payment across multiple methods, and post revenue to the right accounts by category.' },
      { title: 'Occupancy and revenue reporting', text: 'Occupancy, average rate and revenue by room type, computed from posted stays rather than estimated.' },
    ],
    outcomes: [
      { value: 'One folio', label: 'Per stay, across every charge type' },
      { value: 'By category', label: 'Revenue split between rooms, food and services' },
      { value: 'Template', label: 'Bulk room and rate setup from a spreadsheet' },
    ],
    howItWorks: [
      { step: 'Set up rooms and rates', text: 'Loaded in bulk from the downloadable template.' },
      { step: 'Book and check in', text: 'The stay opens a folio that charges accumulate against.' },
      { step: 'Check out and settle', text: 'One bill, multiple payment methods, correctly split revenue postings.' },
    ],
    worksWith: ['pos', 'sales', 'journals', 'reports'],
    faqs: [
      { q: 'Can restaurant sales go onto a room bill?', a: 'Yes. With POS enabled alongside Accommodations, a charge taken at the restaurant till can be posted to an open guest folio instead of settled as a separate cash sale.' },
      { q: 'Is it suitable for short-let and serviced apartments?', a: 'Yes. Anything billed as a stay with incidental charges works the same way, whatever you call the unit.' },
    ],
  },

  /* --------------------------------------------------------------- people -- */
  {
    slug: 'employees',
    name: 'Employees',
    category: 'people',
    tier: 'free',
    billable: true,
    eyebrow: 'Employees',
    title: 'One record per person, and the access that goes with it',
    summary: 'Employee records, documents, employment terms and the role-based access that governs what each person can do.',
    lede: 'The staff list is not an HR formality. It is the access control list for the whole platform. Who someone is, what they are paid, and what they are allowed to post are the same record.',
    heroImage: 'teamMeeting',
    cardImage: 'happyEmployee',
    capabilities: [
      { title: 'Complete employee records', text: 'Personal details, contact information, next of kin, bank details for payment, and employment history in one profile.' },
      { title: 'Employment terms that drive payroll', text: 'Salary, allowances, standing deductions and pay frequency live on the record, so the pay run reads them rather than being retyped.' },
      { title: 'Role and access assignment', text: 'A person’s profile determines what they can open, change, approve and export across every module.' },
      { title: 'Documents and compliance', text: 'Contracts, identification and certifications attached to the person, with expiry visibility.' },
      { title: 'Joiners and leavers', text: 'Onboard with the right access from day one, and revoke it completely on departure in one action.' },
      { title: 'Included on every plan', text: 'Employees, Departments, Positions and Attendance are free core modules, so you never pay to keep your own staff records.' },
    ],
    outcomes: [
      { value: 'Free', label: 'Core HR modules on every plan, permanently' },
      { value: '1', label: 'Record driving both pay and system access' },
      { value: 'Unlimited', label: 'Users on every workspace, on every plan' },
    ],
    howItWorks: [
      { step: 'Create the person', text: 'Details, terms and bank information.' },
      { step: 'Place them in the structure', text: 'Department and position, which sets reporting and defaults.' },
      { step: 'Grant access', text: 'Assign the profile that defines what they can do in the platform.' },
    ],
    worksWith: ['attendance', 'payroll', 'departments', 'settings'],
    faqs: [
      { q: 'Is there a per-user charge?', a: 'No. Every plan includes unlimited users on the workspace. Pricing is per module, never per head.' },
      { q: 'Can I store contracts and ID documents?', a: 'Yes, attached to the employee record, with visibility of expiry dates for anything time-limited.' },
    ],
  },
  {
    slug: 'departments',
    name: 'Departments & Positions',
    category: 'people',
    tier: 'free',
    billable: true,
    eyebrow: 'Departments & positions',
    title: 'The shape of the organisation, and what it costs',
    summary: 'Departments, positions, reporting lines and cost attribution, so you can see performance by part of the business.',
    lede: 'Departments are not an org chart exercise. They are how payroll cost, expenses and revenue get attributed to the part of the business that caused them, which is the only way to know which parts actually pay.',
    heroImage: 'executiveMeeting',
    cardImage: 'teamWorking',
    capabilities: [
      { title: 'Department structure', text: 'Define the real divisions of your business, whether that is kitchen, floor, warehouse, finance or each separate branch, then place people in them.' },
      { title: 'Positions and grades', text: 'Standardise roles with default terms, so a new hire into an existing position starts from the right baseline.' },
      { title: 'Cost attribution', text: 'Payroll and expenses carry their department, so you can see what each part of the business costs to run.' },
      { title: 'Reporting lines and approvals', text: 'Approval routing can follow the structure, so requests reach the right manager automatically.' },
      { title: 'Headcount visibility', text: 'Current and historical headcount by department, derived from the employee records themselves.' },
      { title: 'Free on every plan', text: 'Part of the free core module set, alongside Employees, Attendance, Dashboard and Settings.' },
    ],
    outcomes: [
      { value: 'By department', label: 'Payroll and expense attribution' },
      { value: 'Free', label: 'Included on every plan, permanently' },
      { value: 'Structural', label: 'Approval routing follows reporting lines' },
    ],
    howItWorks: [
      { step: 'Define departments', text: 'The real operating divisions, including per branch where relevant.' },
      { step: 'Define positions', text: 'With default terms, so hiring into them is consistent.' },
      { step: 'Costs attribute themselves', text: 'Payroll and expenses carry the department through to reporting.' },
    ],
    worksWith: ['employees', 'payroll', 'expenses', 'reports'],
    faqs: [
      { q: 'Do I need Departments to run Payroll?', a: 'Yes. Payroll depends on Employees, Attendance, Departments and Positions, all of which are free core modules, so enabling Payroll does not add cost beyond Payroll itself.' },
    ],
  },
  {
    slug: 'attendance',
    name: 'Attendance',
    category: 'people',
    tier: 'free',
    billable: true,
    eyebrow: 'Attendance',
    title: 'Hours that are recorded, approved, and actually used',
    summary: 'Time capture, shift patterns, absence and approval, feeding straight into the pay run with no re-entry.',
    lede: 'Attendance only matters if it reaches payroll. Here it does: approved hours are what the pay run reads, so the argument about who worked which Saturday happens before payday, not after it.',
    heroImage: 'workingOffice',
    cardImage: 'officeWorker',
    capabilities: [
      { title: 'Clock-in capture', text: 'Record attendance at the point it happens, including from biometric and terminal data brought in from the floor.' },
      { title: 'Shifts and patterns', text: 'Define the working patterns your business actually runs, including split shifts and weekend rotations.' },
      { title: 'Overtime and absence', text: 'Capture overtime, leave, sickness and unpaid absence distinctly, because they are paid differently.' },
      { title: 'Supervisor approval', text: 'Hours are reviewed and approved before they are payable, with the approver recorded.' },
      { title: 'Straight into payroll', text: 'Approved hours are the input to the pay run. No export, no retyping, no second spreadsheet.' },
      { title: 'Exception reporting', text: 'Missing clock-outs, impossible shifts and repeated lateness are surfaced rather than left to be noticed.' },
    ],
    outcomes: [
      { value: '0', label: 'Re-entry between attendance and payroll' },
      { value: 'Approved', label: 'Hours only become payable after sign-off' },
      { value: 'Free', label: 'Included on every plan' },
    ],
    howItWorks: [
      { step: 'Hours are captured', text: 'At a terminal, on a device, or imported from clock hardware.' },
      { step: 'Supervisor approves', text: 'Exceptions resolved before the period closes.' },
      { step: 'Payroll reads it', text: 'The pay run is calculated from approved hours directly.' },
    ],
    worksWith: ['employees', 'payroll', 'departments', 'reports'],
    faqs: [
      { q: 'Can I import from a fingerprint clock?', a: 'Yes. Attendance data captured on floor hardware can be brought in and reconciled against employee records rather than keyed by hand.' },
    ],
  },
  {
    slug: 'payroll',
    name: 'Payroll',
    category: 'people',
    tier: 'standard',
    billable: true,
    eyebrow: 'Payroll',
    title: 'Paying people correctly, every time, without a separate spreadsheet',
    summary: 'Pay runs calculated from approved attendance, with allowances, statutory and custom deductions, payslips and ledger postings.',
    lede: 'Payroll is the process with the least tolerance for being approximately right. It reads approved hours and contract terms, applies your deduction rules, produces payslips, and posts the cost and the liability to the ledger.',
    heroImage: 'budgetPlanning',
    cardImage: 'accountant',
    capabilities: [
      { title: 'Calculated from approved attendance', text: 'The pay run reads hours that a supervisor has already signed off, so the inputs are settled before the money moves.' },
      { title: 'Allowances and deductions', text: 'Tax, pension and statutory deductions, alongside your own rules for loans, advances, levies and union dues. All applied the same way every run.' },
      { title: 'Salary advances and recovery', text: 'Advance against future pay and recover it over agreed periods, with the outstanding balance visible rather than remembered.' },
      { title: 'Payslips staff can read', text: 'An itemised payslip per employee showing what was earned, what was deducted and why, which is what stops most payday disputes.' },
      { title: 'Paid, pending and owed', text: 'See what has been paid, what is still outstanding and what the business owes in salary liabilities at any point.' },
      { title: 'Posts to the ledger automatically', text: 'Gross cost, each deduction liability and net payable post to their mapped accounts as part of the run.' },
      { title: 'Department cost attribution', text: 'Payroll cost carries its department through to reporting, so you can see what each part of the business costs.' },
      { title: 'Run history and re-run safety', text: 'Every run is a record. Corrections are made as adjustments with an audit trail, not by editing history.' },
    ],
    outcomes: [
      { value: 'From hours', label: 'Pay calculated directly from approved attendance' },
      { value: 'Itemised', label: 'Payslip per employee, every run' },
      { value: 'Auto', label: 'Cost and liability posted to the ledger' },
    ],
    howItWorks: [
      { step: 'Close attendance', text: 'Supervisors approve the period’s hours and resolve exceptions.' },
      { step: 'Run payroll', text: 'Terms, hours, allowances and deductions are applied.' },
      { step: 'Review and approve', text: 'The run is checked and signed off before payment.' },
      { step: 'Pay and post', text: 'Payslips issue; cost, deductions and net pay post to the accounts.' },
    ],
    worksWith: ['attendance', 'employees', 'departments', 'journals'],
    faqs: [
      { q: 'What does Payroll depend on?', a: 'Employees, Attendance, Departments and Positions. All four are free core modules, so Payroll is the only part of that chain you pay for.' },
      { q: 'Can I handle salary advances?', a: 'Yes. Advances are recorded against the employee and recovered over the periods you agree, with the outstanding balance tracked rather than relied on memory.' },
      { q: 'Does it post to the accounts?', a: 'Yes. Gross cost, each deduction liability and net pay post to the accounts mapped in Settings as part of the run.' },
    ],
  },
  {
    slug: 'business-partners',
    name: 'Business Partners',
    category: 'people',
    tier: 'standard',
    billable: true,
    eyebrow: 'Business Partners',
    title: 'A real ledger behind every relationship',
    summary: 'Customers and vendors as proper accounts with balances, history, credit terms and ageing, not just a name on a document.',
    lede: 'A customer is not a text field on an invoice. It is a running balance, a payment history and a credit position. Business Partners makes every trading relationship an account you can open and interrogate.',
    heroImage: 'handshake',
    cardImage: 'consultation',
    capabilities: [
      { title: 'Customer and vendor accounts', text: 'One record per trading relationship, with contact details, terms and the full document history attached.' },
      { title: 'Running balances', text: 'What each customer owes and what you owe each vendor, kept in step with the ledger rather than tallied separately.' },
      { title: 'Ageing analysis', text: 'How long each balance has been outstanding, so collections effort goes where it is actually needed.' },
      { title: 'Credit limits and terms', text: 'Payment terms and credit limits per partner, with the limit enforced at the point of sale rather than discovered later.' },
      { title: 'Statements', text: 'Produce a statement of account for any partner over any period, straight from posted transactions.' },
      { title: 'Full document history', text: 'Every order, invoice, receipt, credit note and payment against that partner, in one chronological view.' },
    ],
    outcomes: [
      { value: 'Per partner', label: 'Running balance and full document history' },
      { value: 'Enforced', label: 'Credit limits applied at the point of sale' },
      { value: 'On demand', label: 'Statements built from posted transactions' },
    ],
    howItWorks: [
      { step: 'Create the partner', text: 'Customer, vendor, or both, with terms and limits.' },
      { step: 'Trade', text: 'Sales and purchases attach to the partner automatically.' },
      { step: 'Collect and pay', text: 'Balances, ageing and statements follow from the posted records.' },
    ],
    worksWith: ['sales', 'purchase', 'journals', 'reports'],
    faqs: [
      { q: 'Can one record be both a customer and a supplier?', a: 'Yes. A single partner can carry both a receivable and a payable position, which is common where you buy from and sell to the same business.' },
    ],
  },

  /* -------------------------------------------------------------- finance -- */
  {
    slug: 'journals',
    name: 'Journals & Chart of Accounts',
    category: 'finance',
    tier: 'standard',
    billable: true,
    eyebrow: 'Journals & Chart of Accounts',
    title: 'The part everything else is really built around',
    summary: 'A live double-entry general ledger written to by the operational modules as the business runs, with incremental period closings.',
    lede: 'Most small-business systems bolt accounting on at the end. Here it is the foundation: a sale, a goods receipt, a pay run and an expense each produce real double-entry postings at the moment they happen.',
    heroImage: 'accountantDesk',
    cardImage: 'bookkeeping',
    capabilities: [
      { title: 'Chart of accounts you control', text: 'Build the account structure your accountant wants, then map operational activity to it once in Settings.' },
      { title: 'Postings from operations, automatically', text: 'Sales, purchases, stock movement, payroll and expenses generate their own balanced entries. The ledger is a by-product of trading, not a monthly project.' },
      { title: 'Manual journals with control', text: 'Accruals, corrections and adjustments can be posted by hand, under permission, with narration and an audit trail.' },
      { title: 'Incremental period closings', text: 'Closing a period stores a snapshot, so the next period’s figures are computed forward from it rather than recomputing the whole history every time.' },
      { title: 'Ledger drill-down', text: 'Move from a COA balance to the ledger, to the individual entries, to the operational document that created them.' },
      { title: 'Multi-location, one ledger', text: 'Branch activity posts to the same chart of accounts, so consolidated figures and per-branch figures come from one place.' },
      { title: 'Reversals, not deletions', text: 'A posted entry is corrected by a reversing entry, so history is never silently rewritten.' },
    ],
    outcomes: [
      { value: 'Double entry', label: 'Behind every operational transaction' },
      { value: 'Incremental', label: 'Closings, so performance holds as history grows' },
      { value: 'Drill-down', label: 'From balance to source document' },
    ],
    howItWorks: [
      { step: 'Set up the chart', text: 'Accounts defined, then operational activity mapped to them.' },
      { step: 'The business runs', text: 'Each operational transaction posts its own balanced entries.' },
      { step: 'Close the period', text: 'A snapshot is stored and the next period computes forward from it.' },
    ],
    worksWith: ['reports', 'expenses', 'sales', 'payroll'],
    faqs: [
      { q: 'Do I need accounting knowledge to use it?', a: 'To run the business, no. The postings happen automatically from the operational modules. To design the chart of accounts and the mapping, yes, and it is worth having your accountant do that once at setup.' },
      { q: 'Why does Journals depend on Expenses?', a: 'Because operating costs are the one category that has no other operational module to originate from. Enabling Journals adds Expenses so the ledger is not missing a whole side of the business.' },
    ],
  },
  {
    slug: 'reports',
    name: 'Reports',
    category: 'finance',
    tier: 'standard',
    billable: true,
    eyebrow: 'Reports',
    title: 'Trial balance, P&L and balance sheet, from the actual ledger',
    summary: 'Statutory and management reporting computed from posted entries, exportable, and traceable back to source.',
    lede: 'A report that cannot be traced to its transactions is an opinion. Every figure in every statement here opens into the ledger entries behind it, and from there into the operational document that caused them.',
    heroImage: 'financialAnalysis',
    cardImage: 'businessFinance',
    capabilities: [
      { title: 'Trial balance', text: 'Every account with its debit and credit position for the period, computed from posted entries.' },
      { title: 'Profit & loss', text: 'Revenue, cost of sales, gross margin and operating costs, by period, by branch and by department.' },
      { title: 'Balance sheet', text: 'Assets, liabilities and equity as at any date, including stock value and receivable and payable positions.' },
      { title: 'Management reporting', text: 'Sales by item, margin by category, stock valuation, payroll cost by department, expense analysis and partner ageing.' },
      { title: 'Traceable figures', text: 'Click any line to open the entries behind it, then the operational document behind those.' },
      { title: 'Export for your accountant', text: 'Export to spreadsheet and PDF, so the people who need it outside the platform can work with it.' },
      { title: 'Closing-aware periods', text: 'Reports respect period closings, so a closed month does not quietly change after it has been signed off.' },
    ],
    outcomes: [
      { value: 'From the ledger', label: 'Not from a separate reporting copy' },
      { value: 'Traceable', label: 'Every figure opens to its source transactions' },
      { value: 'Export', label: 'Spreadsheet and PDF for external advisers' },
    ],
    howItWorks: [
      { step: 'Choose a period', text: 'Any range; closed periods are locked to their signed-off figures.' },
      { step: 'Report is computed', text: 'From the last closing snapshot forward, not from the beginning of time.' },
      { step: 'Trace or export', text: 'Drill into any figure, or export the statement.' },
    ],
    worksWith: ['journals', 'sales', 'inventory', 'payroll'],
    faqs: [
      { q: 'Does Reports require Journals?', a: 'Yes. Statements are computed from the general ledger, so Journals & COA is added automatically when Reports is enabled.' },
      { q: 'Can my external accountant get access?', a: 'Yes. Give them a user profile scoped to reporting and ledger access only, with no ability to change operational records.' },
    ],
  },
  {
    slug: 'expenses',
    name: 'Expenses',
    category: 'finance',
    tier: 'standard',
    billable: true,
    eyebrow: 'Expenses',
    title: 'Everything the business spends, categorised and accounted for',
    summary: 'Operating costs captured, categorised, approved and posted, with receipts attached and the department they belong to.',
    lede: 'Rent, fuel, repairs, levies, the generator diesel. The costs that never pass through a purchase order are exactly the ones that disappear from the picture. Expenses is where they get recorded properly.',
    heroImage: 'businessFinance',
    cardImage: 'financialAdvisor',
    capabilities: [
      { title: 'Capture at the point of spend', text: 'Record the cost when it happens, with the receipt attached, rather than reconstructing it from a bank statement weeks later.' },
      { title: 'Categories mapped to accounts', text: 'Each expense category maps to a ledger account once, so posting is consistent and nobody has to decide where it goes each time.' },
      { title: 'Approval thresholds', text: 'Spend above a limit routes to an approver, with the decision and the approver recorded.' },
      { title: 'Department and branch attribution', text: 'Costs carry where they were incurred, so you can see what each part of the business actually consumes.' },
      { title: 'Recurring costs', text: 'Rent, subscriptions and standing charges recorded on a schedule rather than remembered each month.' },
      { title: 'Straight into the P&L', text: 'Every approved expense posts to its mapped account immediately and appears in the period’s figures.' },
    ],
    outcomes: [
      { value: 'At source', label: 'Captured when spent, with the receipt' },
      { value: 'Mapped once', label: 'Category to ledger account, applied consistently' },
      { value: 'By department', label: 'Cost attribution through to reporting' },
    ],
    howItWorks: [
      { step: 'Record the spend', text: 'Amount, category, department and receipt.' },
      { step: 'Approve if needed', text: 'Thresholds route it to the right person.' },
      { step: 'Posts to the ledger', text: 'Immediately, to the mapped account.' },
    ],
    worksWith: ['journals', 'reports', 'purchase', 'assets'],
    faqs: [
      { q: 'What is the difference between Expenses and Purchase?', a: 'Purchase is for goods you receive into stock, with an order, a receipt and an invoice to match. Expenses is for operating costs that never become stock: rent, fuel, repairs, services.' },
    ],
  },
  {
    slug: 'assets',
    name: 'Assets',
    category: 'finance',
    tier: 'standard',
    billable: true,
    eyebrow: 'Fixed Assets',
    title: 'Everything the business owns, on the books properly',
    summary: 'A fixed asset register covering acquisition, depreciation, location, custody and disposal, posting to the ledger throughout.',
    lede: 'A delivery van is not an expense. It is an asset that loses value over years, sits somewhere, belongs to someone’s custody, and eventually gets sold. Treating it as a single payment distorts every statement it touches.',
    heroImage: 'deliveryVan',
    cardImage: 'factoryPlant',
    capabilities: [
      { title: 'Asset register', text: 'Every significant item the business owns, with cost, acquisition date, supplier and identifying details.' },
      { title: 'Depreciation', text: 'Scheduled depreciation posted to the ledger over the asset’s useful life, so the balance sheet reflects current carrying value.' },
      { title: 'Location and custody', text: 'Where each asset is and who is responsible for it, which is how you find out something has gone missing before the audit does.' },
      { title: 'Maintenance history', text: 'Servicing and repair recorded against the asset, so total cost of ownership is visible rather than scattered across expense lines.' },
      { title: 'Disposal and write-off', text: 'Sell or retire an asset with the gain or loss calculated and posted correctly.' },
      { title: 'Capital versus revenue', text: 'Keeps capital expenditure out of the P&L and in the balance sheet, where it belongs.' },
    ],
    outcomes: [
      { value: 'Scheduled', label: 'Depreciation posted automatically to the ledger' },
      { value: 'Per asset', label: 'Location, custody and maintenance history' },
      { value: 'Correct', label: 'Capital spend on the balance sheet, not the P&L' },
    ],
    howItWorks: [
      { step: 'Register the asset', text: 'Cost, date, category, location and custodian.' },
      { step: 'Depreciate over life', text: 'Posted to the ledger on schedule.' },
      { step: 'Dispose when done', text: 'Gain or loss calculated and posted.' },
    ],
    worksWith: ['expenses', 'journals', 'reports', 'purchase'],
    faqs: [
      { q: 'How do I decide what is an asset?', a: 'Your accounting policy sets the capitalisation threshold, usually a value floor plus a useful life of over a year. Anything below it belongs in Expenses.' },
    ],
  },
]

export const PRODUCT_BY_SLUG = PRODUCTS.reduce((acc, product) => {
  acc[product.slug] = product
  return acc
}, {})

export const productsInCategory = (key) => PRODUCTS.filter((p) => p.category === key)

export default PRODUCTS
