/* ============================================================================
   Content for /resources (filterable library) and /events.
   ----------------------------------------------------------------------------
   The library mirrors the resource-centre pattern used by every major ERP
   vendor: one pool of items, three filter axes (type, topic, industry), and
   a small number of promoted entries. Everything is routed to a real
   destination — mostly the documentation and help pages that already exist —
   rather than to a download gate that is not built.

   Items marked `gated: false` genuinely open in-app. Anything that would need
   an asset the platform does not host yet points at the relevant doc section
   instead of a dead PDF link.
   ========================================================================= */

export const RESOURCE_TYPES = ['All types', 'Guide', 'Checklist', 'Template', 'Webinar', 'Article', 'Documentation']
export const RESOURCE_TOPICS = [
  'All topics',
  'Getting started',
  'Accounting',
  'Inventory',
  'Point of Sale',
  'Payroll & people',
  'Reporting',
  'Security',
  'AI',
]

export const RESOURCES = [
  {
    slug: 'first-thirty-days',
    type: 'Guide',
    topic: 'Getting started',
    title: 'Your first thirty days on Enterprise Compute',
    text: 'A week-by-week implementation plan covering opening balances, stock counts, staff access, account mapping and your first clean period close.',
    image: 'businessTraining',
    minutes: 14,
    featured: true,
    to: '/docs',
  },
  {
    slug: 'chart-of-accounts-design',
    type: 'Guide',
    topic: 'Accounting',
    title: 'Designing a chart of accounts you will not regret',
    text: 'How to structure accounts so operational activity maps cleanly, departmental reporting works, and your accountant does not have to restructure it in a year.',
    image: 'accountantDesk',
    minutes: 11,
    featured: true,
    to: '/docs',
  },
  {
    slug: 'stock-count-checklist',
    type: 'Checklist',
    topic: 'Inventory',
    title: 'The stock count checklist',
    text: 'What to freeze, what to count, how to record variance with a reason, and how to stop the same gap reappearing next quarter.',
    image: 'inventoryCount',
    minutes: 6,
    to: '/docs',
  },
  {
    slug: 'opening-balances-template',
    type: 'Template',
    topic: 'Getting started',
    title: 'Opening balances and item catalogue templates',
    text: 'The spreadsheet templates used to load your item catalogue, opening stock quantities, rooms and rate plans without typing them one at a time.',
    image: 'bookkeeping',
    minutes: 4,
    to: '/docs',
  },
  {
    slug: 'cash-accountability',
    type: 'Guide',
    topic: 'Point of Sale',
    title: 'Making cash variance somebody’s responsibility',
    text: 'Why session-based handling changes behaviour, how to set opening floats, and what to do the first time a shift is genuinely short.',
    image: 'posTerminal',
    minutes: 9,
    to: '/products/pos',
  },
  {
    slug: 'attendance-to-payroll',
    type: 'Guide',
    topic: 'Payroll & people',
    title: 'From the clock to the payslip, without re-entry',
    text: 'Setting up shift patterns, approval responsibility and deduction rules so the pay run reads attendance directly.',
    image: 'workingOffice',
    minutes: 10,
    to: '/products/payroll',
  },
  {
    slug: 'closing-a-period',
    type: 'Guide',
    topic: 'Accounting',
    title: 'Closing a period on a running ledger',
    text: 'What a closing snapshot actually stores, why it makes later periods faster, and how to handle an adjustment to a closed month properly.',
    image: 'financialAnalysis',
    minutes: 12,
    to: '/products/journals',
  },
  {
    slug: 'permissions-model',
    type: 'Guide',
    topic: 'Security',
    title: 'Designing permissions for a business that is growing',
    text: 'Per-action permissions, approval thresholds and the profiles most operators end up needing: cashier, supervisor, storekeeper, accountant, owner.',
    image: 'cyberSecurity',
    minutes: 8,
    to: '/products/settings',
  },
  {
    slug: 'offline-operations',
    type: 'Article',
    topic: 'Point of Sale',
    title: 'What actually happens when the network drops',
    text: 'The local queue, client transaction ids, ordered replay and how conflicts are surfaced rather than silently resolved.',
    image: 'shopkeeper',
    minutes: 7,
    to: '/products/offline-sync',
  },
  {
    slug: 'asking-epsilon-well',
    type: 'Article',
    topic: 'AI',
    title: 'Getting useful answers out of Epsilon',
    text: 'The kinds of question that work, such as tracing a number, finding a blocker or identifying an approver, and why it will never change anything without you.',
    image: 'dataAnalytics',
    minutes: 6,
    to: '/products/epsilon',
  },
  {
    slug: 'reading-your-reports',
    type: 'Guide',
    topic: 'Reporting',
    title: 'Reading a trial balance you did not prepare',
    text: 'A practical walkthrough for owners and operations leads: what each statement tells you, and how to drill from a figure to the transaction behind it.',
    image: 'businessFinance',
    minutes: 13,
    to: '/products/reports',
  },
  {
    slug: 'multi-site-rollout',
    type: 'Guide',
    topic: 'Getting started',
    title: 'Rolling out across several sites',
    text: 'Sequencing locations, handling inter-branch transfers from day one, and avoiding the consolidated-reporting trap.',
    image: 'warehouseLogistics',
    minutes: 11,
    to: '/services',
  },
  {
    slug: 'margin-by-item',
    type: 'Article',
    topic: 'Reporting',
    title: 'Why your margin report has been lying to you',
    text: 'Assumed markup, unattributed landed cost and unrecorded wastage. These are the three reasons reported margin and real margin drift apart.',
    image: 'dataDashboard',
    minutes: 8,
    to: '/products/reports',
  },
  {
    slug: 'module-dependencies',
    type: 'Documentation',
    topic: 'Getting started',
    title: 'How module dependencies and pricing work',
    text: 'Which modules are free forever, which are priced, what gets added automatically when you enable something, and when a price change takes effect.',
    image: 'officeLaptop',
    minutes: 5,
    to: '/pricing',
  },
  {
    slug: 'security-practices',
    type: 'Documentation',
    topic: 'Security',
    title: 'Security, tenancy and data handling',
    text: 'Tenant isolation, access control, audit trails, encryption in transit and at rest, and what happens to your data if you leave.',
    image: 'dataCentre',
    minutes: 9,
    to: '/trust-center',
  },
]

/* ---------------------------------------------------------------- events -- */

export const EVENT_TYPES = ['All formats', 'Webinar', 'Workshop', 'Office hours', 'On-demand']

export const EVENTS = [
  {
    slug: 'getting-live-in-30-days',
    type: 'Webinar',
    title: 'Getting live in thirty days: a practical implementation session',
    text: 'A walk through a real implementation sequence, covering opening balances, stock load, account mapping, staff access and the first close, with time for questions.',
    image: 'businessPresentation',
    when: 'Second Tuesday of each month',
    duration: '60 minutes',
    format: 'Online, live',
    featured: true,
  },
  {
    slug: 'accounting-foundations',
    type: 'Workshop',
    title: 'Accounting foundations for operators',
    text: 'For owners and operations leads who read the statements but did not train in accounting. What the ledger is doing underneath, and how to interrogate it.',
    image: 'classroomTraining',
    when: 'Monthly',
    duration: '2 hours',
    format: 'Online, live',
  },
  {
    slug: 'pos-and-cash',
    type: 'Workshop',
    title: 'POS, sessions and cash accountability',
    text: 'Setting up tills, floats and shift sessions, and handling the operational and human side of the first genuine variance.',
    image: 'posCheckout',
    when: 'Monthly',
    duration: '90 minutes',
    format: 'Online, live',
  },
  {
    slug: 'inventory-deep-dive',
    type: 'Webinar',
    title: 'Inventory deep dive: movements, transfers and production',
    text: 'How positions are built from movements, how transfers behave in transit, and how production converts components into finished goods.',
    image: 'warehouseRacks',
    when: 'Quarterly',
    duration: '75 minutes',
    format: 'Online, live',
  },
  {
    slug: 'office-hours',
    type: 'Office hours',
    title: 'Open office hours with the product team',
    text: 'No agenda. Bring a configuration question, a workflow you are stuck on, or a feature you want to argue for.',
    image: 'teamCollaboration',
    when: 'Every other Thursday',
    duration: '45 minutes',
    format: 'Online, live',
  },
  {
    slug: 'epsilon-in-practice',
    type: 'On-demand',
    title: 'Epsilon in practice: tracing a number end to end',
    text: 'A recorded session following a single disputed figure from the dashboard, through the ledger, to the operational document that caused it.',
    image: 'realtimeDashboard',
    when: 'Available now',
    duration: '32 minutes',
    format: 'Recording',
  },
  {
    slug: 'multi-site-operations',
    type: 'On-demand',
    title: 'Running multiple sites on one workspace',
    text: 'Locations, transfers, per-branch cash and consolidated reporting, recorded from the live workshop.',
    image: 'supermarketAisle',
    when: 'Available now',
    duration: '48 minutes',
    format: 'Recording',
  },
  {
    slug: 'payroll-walkthrough',
    type: 'On-demand',
    title: 'A complete payroll run, start to finish',
    text: 'From closing attendance through deductions and approval to payslips and the resulting ledger postings.',
    image: 'budgetPlanning',
    when: 'Available now',
    duration: '41 minutes',
    format: 'Recording',
  },
]

export default RESOURCES
