/* ============================================================================
   Content for /solutions, the "find yourself on this page" entry points.
   ----------------------------------------------------------------------------
   Three axes, the set that netsuite.com and sap.com both converged on and
   that works because buyers arrive thinking in exactly one of them: how big
   am I, what is my job, and what is currently broken. A fourth axis covers
   what the buyer is moving away from.

   Anchors (`id`) are referenced from content/navigation.js, so renaming one
   means updating the nav too.
   ========================================================================= */

export const BY_SIZE = [
  {
    id: 'size-small',
    name: 'Small business',
    shape: 'One site, up to 15 people, the owner still on the floor',
    image: 'shopkeeper',
    lede: 'You do not need an ERP programme. You need the till, the stock and the books to stop disagreeing, without hiring anyone to maintain it.',
    points: [
      'Start on the free trial with every module unlocked, then keep only what you use',
      'Core apps stay free forever: Dashboard, Employees, Departments, Positions, Attendance and Settings',
      'Unlimited users on every plan, so putting the whole team on it costs nothing extra',
      'Runs in a browser; no server to buy, no IT contractor to retain',
    ],
    modules: ['pos', 'inventory', 'sales'],
    cta: { label: 'Start a free trial', to: '/signup' },
  },
  {
    id: 'size-growing',
    name: 'Growing business',
    shape: 'Two to five sites, 15 to 100 people, a real finance function',
    image: 'teamMeeting',
    lede: 'The point where spreadsheets stop scaling and everybody starts keeping their own version of the truth. You need one ledger and real permissions.',
    points: [
      'Per-location stock positions with tracked transfers between sites',
      'Role-based access so growth does not mean everyone seeing everything',
      'Approval routing on discounts, write-offs and spend above your thresholds',
      'Consolidated and per-branch reporting from the same posted ledger',
    ],
    modules: ['inventory', 'journals', 'reports', 'payroll'],
    cta: { label: 'Build your plan', to: '/pricing' },
  },
  {
    id: 'size-enterprise',
    name: 'Multi-site enterprise',
    shape: 'Six or more sites, 100+ people, group reporting obligations',
    image: 'executiveMeeting',
    lede: 'Consolidation without a two-year implementation. One chart of accounts, many locations, and reporting that holds up to scrutiny.',
    points: [
      'One chart of accounts across every branch, with per-branch and consolidated views',
      'Incremental period closings so reporting stays fast as history grows',
      'Full audit trail on every posted record, with reversals rather than deletions',
      'Implementation support and custom commercial terms through the Enterprise plan',
    ],
    modules: ['journals', 'reports', 'settings', 'assets'],
    cta: { label: 'Talk to sales', to: '/contact' },
  },
]

export const BY_ROLE = [
  {
    id: 'role-owner',
    name: 'Owner / CEO',
    question: '"Is the business actually making money, and where?"',
    image: 'businessOwner',
    lede: 'One screen that is a read of the ledger rather than a slide somebody prepared. Every figure traces back to a transaction you can open.',
    points: [
      'Live revenue, margin, cash and stock position as of now',
      'Per-branch and per-department performance from the same ledger',
      'Exceptions surfaced, including negative stock, unposted sessions and overdue approvals',
      'Ask Epsilon why a number moved and get the transactions behind it',
    ],
    modules: ['dashboard', 'reports', 'epsilon'],
  },
  {
    id: 'role-finance',
    name: 'Finance lead',
    question: '"Can I close the month without rebuilding it first?"',
    image: 'accountantDesk',
    lede: 'A general ledger written to by operations as they happen, not reconstructed from exports at month-end.',
    points: [
      'Real double-entry postings generated by sales, purchases, payroll and stock movement',
      'Chart of accounts you design, mapped to operational activity once',
      'Incremental closings that compute forward from the last snapshot',
      'Trial balance, P&L and balance sheet traceable to source documents',
    ],
    modules: ['journals', 'reports', 'expenses', 'assets'],
  },
  {
    id: 'role-operations',
    name: 'Operations manager',
    question: '"Does the shelf match the system, and who was on?"',
    image: 'warehouseWorker',
    lede: 'Stock as a running position built from attributed movements, and cash as a session belonging to a named person.',
    points: [
      'Stock position per item per location with full movement history',
      'Transfers tracked in transit, with discrepancies on receipt raised',
      'Session-based cash handling with variance attributed to the operator',
      'Reorder thresholds surfaced before the shelf empties',
    ],
    modules: ['inventory', 'pos', 'purchase', 'delivery'],
  },
  {
    id: 'role-hr',
    name: 'HR & payroll',
    question: '"Can payroll read the hours without me retyping them?"',
    image: 'workingOffice',
    lede: 'Approved attendance is the direct input to the pay run. No export, no second spreadsheet, no payday arguments about Saturdays.',
    points: [
      'Attendance captured, approved by supervisors, then read by payroll',
      'Allowances, statutory and custom deductions applied consistently',
      'Salary advances with recovery tracked rather than remembered',
      'Itemised payslips, and cost attributed by department',
    ],
    modules: ['attendance', 'payroll', 'employees', 'departments'],
  },
  {
    id: 'role-it',
    name: 'IT & systems',
    question: '"What am I actually responsible for running?"',
    image: 'dataCentre',
    lede: 'A browser-delivered, multi-tenant platform with a desktop option for poor connectivity. No servers of yours to patch.',
    points: [
      'Tenant-isolated data with per-action, role-based permissions',
      'Offline-capable clients with a durable local queue and idempotent replay',
      'Full audit trail on every posted record',
      'Desktop build with a bundled local database for low-connectivity sites',
    ],
    modules: ['settings', 'offline-sync', 'epsilon'],
  },
]

export const BY_CHALLENGE = [
  {
    id: 'challenge-stock',
    name: 'Stock never matches the shelf',
    image: 'inventoryCount',
    symptom: 'Counts come out wrong every time and the variance gets written off without anybody finding out why.',
    answer: 'Every change to a stock position is a recorded movement with a date, a document and a person attached. A variance stops being a mystery number and becomes a list of movements you can read.',
    proof: [
      'Sales, purchases, transfers, production and wastage all post as attributed movements',
      'Adjustments require a reason code, so write-offs are explained',
      'Positions are held per location, so a branch gap is not hidden by a group total',
    ],
    modules: ['inventory', 'pos', 'purchase'],
  },
  {
    id: 'challenge-close',
    name: 'Month-end takes weeks',
    image: 'bookkeeping',
    symptom: 'The close is a rebuild: exports, spreadsheets, reconciliations, and figures that change after they were signed off.',
    answer: 'The ledger is written as the business trades. Closing a period stores a snapshot and the next period computes forward from it, so you are confirming figures rather than constructing them.',
    proof: [
      'Operational transactions generate their own balanced double-entry postings',
      'Incremental closings avoid recomputing history every period',
      'Closed periods are locked to their signed-off figures',
    ],
    modules: ['journals', 'reports', 'expenses'],
  },
  {
    id: 'challenge-offline',
    name: 'Sales stop when the network does',
    image: 'posTerminal',
    symptom: 'A connectivity drop means a queue, a paper fallback, and an evening of re-keying that nobody trusts afterwards.',
    answer: 'The client switches to local-first operation, keeps selling against its local copy, and replays the queue in order when the connection returns. Duplicate posting is prevented by client transaction ids.',
    proof: [
      'Pending changes written to IndexedDB so a refresh does not lose them',
      'Idempotent replay, so a half-failed upload cannot double-post a sale',
      'Conflicts raised for a human rather than resolved by last-write-wins',
    ],
    modules: ['offline-sync', 'pos', 'inventory'],
  },
  {
    id: 'challenge-truth',
    name: 'Nobody agrees on the numbers',
    image: 'teamDocuments',
    symptom: 'Sales has one figure, finance has another, and the meeting is spent arguing about which spreadsheet is right.',
    answer: 'There is one record. The sales report and the ledger are two views of the same posted transactions, so they cannot disagree, and both drill down to the same source document.',
    proof: [
      'One posting per transaction, read by every report',
      'Drill-down from any figure to the entries and the operational document behind it',
      'Tenant-scoped live updates, so two people looking at a number see the same number',
    ],
    modules: ['dashboard', 'journals', 'reports'],
  },
]

const solutions = { BY_SIZE, BY_ROLE, BY_CHALLENGE }
export default solutions
